- src/components/gcds-button/gcds-button.tsx
- src/utils/utils.ts
Fixed issue when changing an inherited attribute would remove all other inherited attributes from shadow element. inheritedAttributes now compares itself to the shadow element as well as the host element.
> Fix overwriting of inherited attributes

- src/components/gcds-input/gcds-input.spec.ts
- src/components/gcds-input/gcds-input.tsx
- src/components/gcds-label/gcds-label.tsx
- src/components/gcds-site-menu/gcds-site-menu.tsx
- src/components/gcds-textarea/gcds-textarea.spec.ts
- src/components/gcds-textarea/gcds-textarea.tsx
- src/utils/utils.ts
Added  passing lang attributes from gcds-input and gcds-textarea to gcds-label. When required field needs to show, it should now be bilingual.
> Add bilingual text for required label

- src/components/gcds-site-menu/gcds-site-menu.css
Sorry this took so long, it was slow working :s
Restyling the site menu component. 
The main work that was done here was:
- Replacing the background colour with something more neutral (gray here)
- Aligning the site menu container with the current container
- Adding interactive states for each menu-item (Hover, active, focus)
- Added a media query to ensure the alignment of the site-menu with the container as screen width is reduced.
- There is an issue with the hover state for the `components` link and the submenu trigger clashing on smaller screens (they overlap) that probably can't be resolved without changing the actual structure of the component, so leaving as is for now and we can deal with it in the future
> Site menu styles

- src/components/gcds-input/gcds-input.css
- src/components/gcds-textarea/gcds-textarea.css
Minor update to the focus styles for inputs and textareas to match the focus style that I've mocked up in figma for radio and checkboxes.
[Atoms page to see focus styles](https://www.figma.com/file/4KWj8wnnXoq6cA6yl0dnsR/GC-Components?node-id=479%3A310)
> textarea and input focus update

- src/components/gcds-input/gcds-input.css
- src/components/gcds-input/gcds-input.spec.ts
- src/components/gcds-input/gcds-input.tsx
- src/components/gcds-textarea/gcds-textarea.css
- src/components/gcds-textarea/gcds-textarea.spec.ts
- src/components/gcds-textarea/gcds-textarea.tsx
Based off feedback from #27 update the internal classes of `gcds-input` and `gcds-textarea` to be name spaced classes.
These have been done to avoid some potential issues with some accessibility tools.
- `aria-describedby` now only renders on components when need.
- Removed the `fieldset` in the components and replaced with `<div class="gcds-{component}-wrapper">`
> Update input and textarea components

- src/components.d.ts
- src/components/gcds-fieldset/gcds-fieldset.css
- src/components/gcds-fieldset/gcds-fieldset.tsx
- src/components/gcds-fieldset/test/gcds-fieldset.e2e.ts
- src/components/gcds-fieldset/test/gcds-fieldset.spec.tsx
- src/styles/global.css
Fieldset component for grouping form fields.
``` html
<gcds-fieldset
fieldset-id="string"
legend="string"
required="boolean"
disabled="boolean"
hint="string"
error-message="string"
>
<Slot />
</gcds-fieldset>
```
Pass form elements as children to the `gcds-fieldset` to be grouped together.
Disabling the fieldset will disable all children elements passed to the `gcds-fieldset`. 
Error styles currently only apply to fieldset and legend. Will expand with validators.
> gcds-fieldset

- src/components.d.ts
- src/components/gcds-checkbox/gcds-checkbox.tsx
- src/components/gcds-checkbox/test/gcds-checkbox.e2e.ts
- src/components/gcds-checkbox/test/gcds-checkbox.spec.tsx
- src/components/gcds-fieldset/gcds-fieldset.tsx
- src/components/gcds-file-uploader/gcds-file-uploader.tsx
- src/components/gcds-file-uploader/test/gcds-file-uploader.spec.tsx
- src/components/gcds-input/gcds-input.tsx
- src/components/gcds-radio/gcds-radio.tsx
- src/components/gcds-radio/test/gcds-radio.e2e.ts
- src/components/gcds-radio/test/gcds-radio.spec.tsx
- src/components/gcds-select/gcds-select.tsx
- src/components/gcds-select/test/gcds-select.spec.tsx
- src/components/gcds-textarea/gcds-textarea.tsx
- src/utils/utils.ts
- src/validators/checkbox-validators/checkbox-validators.ts
- src/validators/checkbox-validators/test/checkbox-validators.spec.tsx
- src/validators/fieldset-validators/fieldset-validators.ts
- src/validators/fieldset-validators/test/fieldset-validators.spec.tsx
- src/validators/index.ts
- src/validators/input-validators/input-validators.ts
- src/validators/input-validators/test/input-validators.spec.tsx
- src/validators/validator.factory.ts
- src/validators/validator.ts
Add required prop fields to GCDS form components. If the form component is marked required, the validator will become active.
Validators check the form value and return either `true` or `false` based on if the value passes the validation criteria. If not, the `error-message` prop of the component displays the error message from the validator. 
The validators can be set to validate on `blur`, `submit` and `other`, currently  only `blur` and `other` work at the moment. If the `validate-on` prop is not set and a validator is assigned to the component, `validate-on` will default to `blur`.
- gcds-input
- gcds-textarea
- gcds-select
- gcds-file-uploader
- gcds-checkbox
- gcds-fieldset (currently only works with gcds-checkbox or gcds-radio)
- `has-error` prop has been converted to internal …
> Required field validators

- src/components.d.ts
- src/components/gcds-banner/gcds-banner.css
- src/components/gcds-banner/gcds-banner.tsx
- src/components/gcds-banner/readme.md
- src/components/gcds-banner/test/gcds-banner.e2e.ts
- src/components/gcds-banner/test/gcds-banner.spec.tsx
Remove `destructive` and `warning` role from the banner component in order to better separate the alert and the banner component.
> gcds-banner: remove destructive + warning role

- package.json
- src/components.d.ts
- src/components/gcds-alert/gcds-alert.css
- src/components/gcds-alert/gcds-alert.tsx
- src/components/gcds-alert/readme.md
- src/components/gcds-alert/test/gcds-alert.e2e.ts
- src/components/gcds-alert/test/gcds-alert.spec.tsx
- src/components/gcds-icon/readme.md
- src/styles/global.css
Add gcds-alert component.
Alerts notify users of important and often time-sensitive changes. They are usually positioned at the top of the page to capture the user’s attention and therefore should be concise and used sparingly.
- **alert-heading**: Text for the alert heading
- **alert-role**: Defines the role of the alert
- **hide-close-btn**: Controls if the close button is displayed or not
- **onDismiss**: Callback when the close button is clicked
- **max-content-width**: Defines the container width for the alert content
- **position-fixed**: Controls if the alert is fixed to the top or not
Update: The french translations have been added.
> add gcds-alert component

- lerna.json
- package.json
- packages/react/package.json
- packages/react/src/components/stencil-generated/index.ts
- packages/web/package.json
- packages/web/src/components/gcds-hint/test/gcds-hint.spec.ts
- packages/web/src/components/gcds-site-menu/gcds-site-menu.css
- packages/web/src/components/gcds-site-menu/gcds-site-menu.tsx
- packages/web/src/components/gcds-site-menu/test/gcds-site-menu.spec.tsx
- packages/web/stencil.config.ts
- Fix broken tests
- Fix issue with `gcds-site-menu`: Topbar center alignment wouldn't work without `left` and `right` slot present 
- Fix issue with `gcds-site-menu`: dropdown alignment for second menu in `split` alignment
- More package changes for react package
> Package changes + sitemenu fix

- packages/angular/package.json
- packages/angular/src/lib/stencil-generated/components.ts
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-footer/gcds-footer.tsx
- packages/web/src/components/gcds-footer/readme.md
- packages/web/src/components/gcds-footer/test/gcds-footer.spec.tsx
Change `gcds-footer`'s  `type` prop to `display` to better reflect what the property does.
> Change gcds-footer type prop to display

- packages/angular/src/lib/stencil-generated/components.ts
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs-item.css
- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs-item.tsx
- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs.css
- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs.tsx
- packages/web/src/components/gcds-breadcrumbs/readme.md
- packages/web/src/components/gcds-breadcrumbs/test/gcds-breadcrumbs.e2e.ts
- packages/web/src/components/gcds-breadcrumbs/test/gcds-breadcrumbs.spec.tsx
- styles/global.css
Improvements to breadcrumbs component:
- Nicholas recommended using `chemin de navigation` for breadcrumbs instead of `fil d'Ariane`. We'll include fil d'Ariane as an option for the `other names` section.
- Removed current page to avoid confusion with users.
> improve breadcrumbs component

- renovate.json
Update the Renovate schedule so lock file maintenance is only performed once a month.
- cds-snc/platform-core-services#232
> fix: update lock file maintenance to once a month

- packages/web/src/components.d.ts
- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs-item.css
- packages/web/src/components/gcds-checkbox/gcds-checkbox.css
- packages/web/src/components/gcds-header/gcds-header.tsx
- packages/web/src/components/gcds-header/readme.md
- packages/web/src/components/gcds-radio/gcds-radio.css
- styles/global.css
- Revert hint colour back to black
- Mark langHref + skipToHref in gcds-header as required
> Update checkbox tokens

- packages/web/src/components/gcds-button/gcds-button.css
Additional CSS for `gcds-button` to help `type="link"` buttons render the same as other button types.
> Update link type style to act more like other types

- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-icon/gcds-icon.scss
- packages/web/src/components/gcds-icon/gcds-icon.tsx
- packages/web/stencil.config.ts
Add `@stencil/sass` to handle importing font-awesome into the `gcds-icon` CSS to solve issue with `@import` being blocked by browsers.
> Gcds-icon font-awesome rendering fix

- packages/web/src/components/gcds-grid/gcds-grid.css
- packages/web/src/components/gcds-grid/gcds-grid.tsx
- packages/web/src/components/gcds-grid/test/gcds-grid.spec.ts
Remove `matchMedia` and switch to using inline css variables to enable responsive sizing with `gcds-grid`.
> Add responsive sizing to gcds-grid

- packages/web/src/components/gcds-button/gcds-button.tsx
- packages/web/src/components/gcds-checkbox/gcds-checkbox.tsx
- packages/web/src/components/gcds-fieldset/gcds-fieldset.tsx
- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.tsx
- packages/web/src/components/gcds-input/gcds-input.tsx
- packages/web/src/components/gcds-radio/gcds-radio.tsx
- packages/web/src/components/gcds-select/gcds-select.tsx
- packages/web/src/components/gcds-textarea/gcds-textarea.tsx
- packages/web/src/utils/utils.ts
Update `inheritAttributes` function to look for aria and data attributes by default.
- `hostElement`: web component
- `targetElement`: html element in web component to inherit attributes
- `attributes`: Additional attributes, not aria or data, to inherit
``` js
this.inheritedAttributes =  inheritAttributes( hostElement, targetElement, [attributes] );
```
> Update inheritAttributes function in form components

- README.md
Fixes case of path in French section of `README.md` to match English equivalent.
> [docs] fixes case

- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-button/gcds-button.css
Add new component tokens to support full-width sizing on mobile.
Uses tokens from https://github.com/cds-snc/gcds-tokens/pull/106. Token Pr will have to merged first, and new package version added to this PR. (Merged)
> Add button full-width sizing when on mobile

- packages/web/src/components/gcds-footer/gcds-footer.css
- packages/web/src/components/gcds-footer/gcds-footer.tsx
- packages/web/src/components/gcds-footer/i18n/i18n.js
- packages/web/src/components/gcds-footer/test/gcds-footer.spec.tsx
Flagged in https://github.com/cds-snc/gcds-docs/issues/139. `gcds-footer` was missing an `h2` heading at the start of the footer. Added the heading into the footer to solve the issue.
> Add missing h2 heading to gcds-footer

- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs-item.css
- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs.css
Add additional CSS and tokens to fix display issue when `gcds-breadcrumbs` is using `hide-canada-link`.
Fixes #152 
**Note: Relies on tokens from https://github.com/cds-snc/gcds-tokens/pull/114**
> Fix: Hide chevron on first breadcrumb item

- .github/workflows/compile-and-publish.yml
Update the publish packages action to allow the action to be triggered manually.
> Update compile-and-publish.yml to allow triggering manually

- lerna.json
- packages/angular/package-lock.json
- packages/angular/package.json
- packages/react/package-lock.json
- packages/react/package.json
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-error-summary/gcds-error-summary.stories.tsx
- packages/web/src/components/gcds-error-summary/i18n/i18n.js
- packages/web/src/index.html
- https://github.com/cds-snc/gcds-components/pull/167/commits/fc5ee8e410d85542d25cd273d084a7defdb883ed - Add value to error summary links in storybook story to display error summary instead of blank screen
- https://github.com/cds-snc/gcds-components/pull/167/commits/597f22435ded6fa1804c2af6143fc2ee9a0085b4 - Update french text for error summary default heading
- https://github.com/cds-snc/gcds-components/pull/167/commits/4b0fe7fa7c25cbcf8c00f6b7ca50cd2259f793e5 - Update demo with new UF name + add gcds-container
> add value to error summary links in storybook story

- .github/workflows/compile-and-publish.yml
Update the publish package workflow so that new packages are now also published to the CDN.
Each new package will be published to a versioned directory in the CDN and replace the files for its `@latest` version.  This will allow users to either link to versioned assets or the latest files.  
The flow for the publish step is as follows:
1. Use the `steps.publish.outputs.id` output to determine if a package was published.  The [JS-DevTools/npm-publish action](https://github.com/JS-DevTools/npm-publish#output) only provides this if there was a release in the format of `${name}@${version}`.
2. Sets up AWS credentials to publish to the CDN's S3 bucket.
3. Creates a `./tmp` directory and uses `npm install "$PUBLISHED_PACKAGE"` to download the package's assets.  This is done to make sure the npm …
> feat: publish new packages to CDN

- packages/web/README.md
Replace unpkg links with new CDN links for CDN installation instructions.
> update unpkg links to use new cdn links in CDN instructions

- packages/web/src/components.d.ts
- packages/web/src/components/gcds-lang-toggle/gcds-lang-toggle.stories.tsx
- packages/web/src/components/gcds-pagination/gcds-pagination.css
- packages/web/src/components/gcds-pagination/gcds-pagination.stories.tsx
- packages/web/src/components/gcds-pagination/gcds-pagination.tsx
- packages/web/src/components/gcds-pagination/readme.md
- packages/web/src/components/gcds-pagination/test/gcds-pagination.spec.tsx
- packages/web/src/components/gcds-pagination/utils/render.tsx
- packages/web/src/index.html
Add `gcds-lang-toggle` and `gcds-pagination` to storybook.
`gcds-pagination` will no longer render the previous or next button if no `previous-href` or `next-href` is passed.
The `url` property has been modified to accept and `object` or `string` like the `subLinks` property on the `gcds-footer`.
> gcds-lang-toggle + gcds-pagination stories

- packages/angular/src/lib/stencil-generated/components.ts
- packages/angular/src/lib/stencil-generated/index.ts
- packages/react/src/components/stencil-generated/index.ts
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-card/gcds-card.css
- packages/web/src/components/gcds-card/gcds-card.stories.tsx
- packages/web/src/components/gcds-card/gcds-card.tsx
- packages/web/src/components/gcds-card/readme.md
- packages/web/src/components/gcds-card/test/gcds-card.e2e.ts
- packages/web/src/components/gcds-card/test/gcds-card.spec.tsx
- packages/web/src/index.html
- packages/web/stencil.config.ts
- packages/web/tsconfig.json
Add new `gcds-card` to component library.
```
<gcds-card
type="link"                // link | action
card-title=""              // *required, string
href=""                       // *required, string
title-element="a"     // h3 | h4 | h5 | h6 | a
description=""          // string
tag=""                       // string
img-src=""                 // string
img-alt=""                 // string
>
<slot name=”footer”></slot>
</gcds-card>
```
The link card is used to display information and has no call to action. The card footer is optional to display metadata about the card contents. If the card links to additional information the entire card is interactive.
The action card is used to display information and it contains a call to action in the card footer. Unlike the default card, only the …
> Gcds-card component

- packages/web/package.json
To solve GitHub actions falling to install `@cdssnc/gcds-components` update storybook to use `v7.1.0-rc2`. 
Versions `7.0.*` were all causing a installation failure with `esbuild`.
> Update storybook version to fix GitHub actions

- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.tsx
- packages/web/src/validators/input-validators/input-validators.ts
- packages/web/src/validators/input-validators/test/input-validators.spec.tsx
Update `requiredFileInput` validator used in the `gcds-file-uploader` to read the file input's `FileList` instead of the component's `value, this makes it easier to develop custom file-uploader validators.
> Update requiredFileInput validator

- packages/web/src/components/gcds-label/gcds-label.tsx
- packages/web/src/components/gcds-label/test/gcds-label.spec.ts
Change the way the "(required)" text renders in `gcds-label`. (required) will now have `aria-hidden="true"` so it is no longer included in the accessible names of form components.
> Update required label rendering

- packages/web/src/components/gcds-checkbox/gcds-checkbox.tsx
- packages/web/stencil.config.ts
Small adjustments for better use.
- Add `extra` config option `experimentalImportInjection` to stencil to help using the GCDS components in bundlers such as Vite. Will update to `enableImportInjection` when using `v3` of Stencil. #174 
- As flagged in #204, switch `onChange` on the `gcds-checkbox` to emit the `checked` value instead of `value`.
> Extra config + checkbox fix

- .github/workflows/compile-and-publish.yml
Add instruction `install repo` back into the compile and publish action to support Angular package.
> Fix compile-and-publish action angular publishing

- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.tsx
- packages/web/src/components/gcds-file-uploader/test/gcds-file-uploader.spec.tsx
- packages/web/src/components/gcds-nav-group/gcds-nav-group.tsx
- packages/web/src/components/gcds-side-nav/gcds-side-nav.tsx
- packages/web/src/components/gcds-top-nav/gcds-top-nav.tsx
- packages/web/src/index.html
Couple accessibility fixes for `gcds-file-uploader` and navigation components.
- Modified the button in `gcds-file-uploader` to be a `type="button"` to avoid submitting the form when interacting with the component with Voice control.
- Add `onClick` to 'Upload a file' button to click file input. Voice control software would click the button before the file input
- Removed focus logic to avoid navigation components from stealing focus
- The first item of a dropdown will no longer be focused when dropdowns open from click. Will still focus when using keyboard controls.
> A11y fixes

- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-search/gcds-search.css
- packages/web/src/components/gcds-search/stories/overview.mdx
Use new tokens to fix the `border-radius` of the `gcds-search` component. The `border-end-end-radius` was overwritten by the `border-radius`.
> gcds-search border-radius style fix

- packages/web/src/components/gcds-search/i18n/I18N.js
- packages/web/src/components/gcds-search/test/gcds-search.spec.tsx
French label/placeholder was incorrectly spelled "Recherche dans", fixed to now be "Rechercher dans".
> Fix typo in French label/placeholder

- .github/workflows/compile-and-publish.yml
- .github/workflows/publish-storybook-staging.yml
- .github/workflows/run-tests.yml
- renovate.json
With switching of `staging` to `develop`, the GitHub actions need to be updated as well.
> Update GitHub actions to use new develop branch name

- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.css
- packages/web/src/components/gcds-pagination/gcds-pagination.css
These are changes to align with the figma file more and to make state styles more consistent
- Upload button had only default state when it should function like a secondary button
- Focus styles have been updated on the uploaded file and the remove button
- The remove button hover style was using `border-block-end` which was causing the uploaded file bucket to resize on state changes, it has been updated to use `text-decoration` instead.
| Before |  ![file-upload-before](https://github.com/cds-snc/gcds-components/assets/30609058/049f3338-bd37-4b52-b530-b48042337eb7) |
|--------|---|
| After  |  ![file-upload-after](https://github.com/cds-snc/gcds-components/assets/30609058/2945e96a-d508-4637-bcf3-05af4d5e3e7a) |
- hover text and border color has been applied to the hover state for pages
- …
> Tokens review update

- packages/web/src/components/gcds-signature/stories/gcds-signature.stories.tsx
- packages/web/src/components/gcds-signature/stories/overview.mdx
- packages/web/src/components/gcds-signature/stories/properties.mdx
- I'm working on the signature component pages for the doc site and the code tab needs to use the storybook component builder thingy
- Created a simple story in which you can toggle the language and type of the signature component
> signature storybook events and properties page

- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.tsx
- packages/web/src/components/gcds-file-uploader/test/gcds-file-uploader.spec.tsx
Remove the icon from the file uploader button to match the new design.
> remove icon from file uploader button

- packages/web/src/components/gcds-pagination/gcds-pagination.tsx
- packages/web/src/components/gcds-pagination/i18n/i18n.js
- packages/web/src/components/gcds-pagination/test/gcds-pagination.spec.tsx
Update the French text for pagination's Previous buttons and shorten `Previous` to `Prev` while in mobile list view.
> Update mobile view and French text of pagination component

- packages/web/src/components/gcds-topic-menu/gcds-topic-menu.tsx
Add additional logic checking to see if the theme and topic menu is open in the `focusout` listener. This prevents the menu from being toggled open if the closed menu button had focus on focus out.
> Fix focusout logic in gcds-topic-menu

- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-details/gcds-details.css
- packages/web/src/components/gcds-details/gcds-details.tsx
- packages/web/src/components/gcds-details/test/gcds-details.spec.tsx
- packages/web/src/index.html
Reformat elements in `gcds-details` to no longer use `details` element since the iOS version of Voiceover doesn't seem to recognize the element.
Uses tokens from https://github.com/cds-snc/gcds-tokens/pull/150
> Details accessibility fix

- packages/web/src/components/gcds-pagination/gcds-pagination.css
Update first media query in `gcds-pagination` to happen earlier to prevent overflow with page container.
> Update media query in gcds-pagination

- package-lock.json
- package.json
- packages/react/package-lock.json
- packages/react/package.json
Update typescript to v 5.1.0, fixes [Renovate PR #262 ](https://github.com/cds-snc/gcds-components/pull/262)
> Update typescript to v 5.1.0

- packages/web/src/components/gcds-header/gcds-header.tsx
- packages/web/src/components/gcds-header/test/gcds-header.spec.tsx
Remove the "skip to main content" label from the navigation landmark to avoid confusion when navigating the header using a screen reader.
> Gcds-header: Remove label from nav landmark to avoid confusion

- .github/workflows/compile-and-publish.yml
Sends a log to sentinel when a deployment happens off of the main branch. 
This sends logs when the following actions run: 
- publish-web
- publish-reach-angular
This is related to: https://github.com/cds-snc/platform-core-services/issues/350
> feat: report deployment status to Sentinel

- packages/angular/src/lib/stencil-generated/components.ts
- packages/angular/src/lib/stencil-generated/index.ts
- packages/react/src/components/stencil-generated/index.ts
- packages/web/.storybook/preview-head.html
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-text/gcds-text.css
- packages/web/src/components/gcds-text/gcds-text.tsx
- packages/web/src/components/gcds-text/readme.md
- packages/web/src/components/gcds-text/stories/gcds-text.stories.tsx
- packages/web/src/components/gcds-text/stories/overview.mdx
- packages/web/src/components/gcds-text/stories/properties.mdx
- packages/web/src/components/gcds-text/test/gcds-text.e2e.ts
- packages/web/src/components/gcds-text/test/gcds-text.spec.ts
- packages/web/src/index.html
Add new `gcds-text` component.
Sets the line length to a maximum amount of characters per line to ensure a comfortable, accessible reading length.
Specifies the display behavior of the text.
Adds margin above the text.
Adds margin below the text.
Sets the main style of the text.
Sets the appropriate HTML tags for the selected size.
Indicates if the text should be styled italic or normal. 
Determines the font weight for the text.
> add gcds-text component

- packages/angular/src/lib/stencil-generated/components.ts
- packages/angular/src/lib/stencil-generated/index.ts
- packages/react/src/components/stencil-generated/index.ts
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-sr-only/gcds-sr-only.css
- packages/web/src/components/gcds-sr-only/gcds-sr-only.tsx
- packages/web/src/components/gcds-sr-only/readme.md
- packages/web/src/components/gcds-sr-only/stories/gcds-sr-only.stories.tsx
- packages/web/src/components/gcds-sr-only/stories/overview.mdx
- packages/web/src/components/gcds-sr-only/stories/properties.mdx
- packages/web/src/components/gcds-sr-only/test/gcds-sr-only.e2e.ts
- packages/web/src/components/gcds-sr-only/test/gcds-sr-only.spec.tsx
- packages/web/src/index.html
Add `gcds-sr-only` component to component library.
To use the screen reader only component, simply wrap the text you want hidden in the component
```html
<gcds-sr-only>
Text only available for assistive technologies.
</gcds-sr-only>
```
> Add screen reader only component

- packages/angular/src/lib/stencil-generated/components.ts
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-text/gcds-text.css
- packages/web/src/components/gcds-text/gcds-text.tsx
- packages/web/src/components/gcds-text/readme.md
- packages/web/src/components/gcds-text/stories/gcds-text.stories.tsx
- packages/web/src/components/gcds-text/stories/overview.mdx
- packages/web/src/components/gcds-text/test/gcds-text.spec.ts
- packages/web/src/index.html
Removing `text-style` and `weight` props from the `gcds-text` component to avoid misuse. Including them as props and adding these styles to an entire block of text would lead to a bad and less accessible user experience and therefore they should not be available as default props.
> remove text-style and weight props from gcds-text to avoid misuse

- packages/web/package.json
- packages/web/src/components/gcds-button/gcds-button.css
- packages/web/src/components/gcds-checkbox/gcds-checkbox.css
- packages/web/src/components/gcds-input/gcds-input.css
- packages/web/src/components/gcds-pagination/gcds-pagination.css
- packages/web/src/components/gcds-radio/gcds-radio.css
- packages/web/src/components/gcds-select/gcds-select.css
- packages/web/src/components/gcds-textarea/gcds-textarea.css
- packages/web/src/index.html
Add additional CSS and tokens for a focus `box-shadow` in `gcds-button`, `gcds-checkbox`, `gcds-input`, `gcds-pagination`, `gcds-radio`, `gcds-select` and `gcds-textarea` to be consistent with other components.
Depends on https://github.com/cds-snc/gcds-tokens/pull/177
> Update focus styles for consistent look

- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs-item.css
With the new slot CSS added to the components, the `gcds-breadcrumbs-items` component no longer had a text underline. Modified the slot CSS to display the underline properly.
> fix: Change slot CSS in gcds-breadcrumbs to display text underline

- .github/workflows/compile-and-publish.yml
Update the CDN publish step to sleep for `60s` so that the npm publish has time to complete.
> fix: give `npm publish` time to complete

- packages/web/src/index.html
Update the demo page to use the gcds-heading component instead of plain heading tags.
> update demo page to use gcds-heading component

- packages/web/src/components/gcds-link/gcds-link.tsx
- packages/web/src/components/gcds-link/test/gcds-link.spec.ts
The external icon for the link component was using `margin-left="200"` instead of `margin-left="100"` like the other icons for this component. Fixed the value to `100` to be consistent.
> fix gcds-link external icon spacing

- packages/web/.storybook/manager-head.html
- packages/web/.storybook/preview-head.html
- packages/web/src/components/gcds-breadcrumbs/stories/gcds-breadcrumbs.stories.tsx
- packages/web/src/components/gcds-button/stories/gcds-button.stories.js
- packages/web/src/components/gcds-card/stories/gcds-card.stories.tsx
- packages/web/src/components/gcds-checkbox/stories/gcds-checkbox.stories.tsx
- packages/web/src/components/gcds-container/stories/gcds-container.stories.tsx
- packages/web/src/components/gcds-details/stories/gcds-details.stories.tsx
- packages/web/src/components/gcds-error-summary/stories/gcds-error-summary.stories.tsx
- packages/web/src/components/gcds-fieldset/stories/gcds-fieldset.stories.tsx
- packages/web/src/components/gcds-file-uploader/stories/gcds-file-uploader.stories.tsx
- packages/web/src/components/gcds-footer/stories/gcds-footer.stories.tsx
- packages/web/src/components/gcds-header/stories/gcds-header.stories.tsx
- packages/web/src/components/gcds-heading/stories/gcds-heading.stories.tsx
- packages/web/src/components/gcds-icon/stories/gcds-icon.stories.tsx
- packages/web/src/components/gcds-input/stories/gcds-input.stories.tsx
- packages/web/src/components/gcds-nav-group/stories/gcds-nav-group.stories.tsx
- packages/web/src/components/gcds-nav-link/stories/gcds-nav-link.stories.tsx
- packages/web/src/components/gcds-pagination/stories/gcds-pagination.stories.tsx
- packages/web/src/components/gcds-radio/stories/gcds-radio.stories.tsx
- packages/web/src/components/gcds-search/stories/gcds-search.stories.tsx
- packages/web/src/components/gcds-select/stories/gcds-select.stories.tsx
- packages/web/src/components/gcds-signature/stories/gcds-signature.stories.tsx
- packages/web/src/components/gcds-text/stories/gcds-text.stories.tsx
- packages/web/src/components/gcds-textarea/stories/gcds-textarea.stories.tsx
- packages/web/src/components/gcds-top-nav/stories/gcds-top-nav.stories.tsx
- packages/web/src/components/gcds-topic-menu/stories/gcds-topic-menu.stories.tsx
- packages/web/src/components/gcds-verify-banner/stories/gcds-verify-banner.stories.tsx
In our last round of Fable testing, some users pointed out that it was really hard to see where the focus was when interacting with our live demo control elements. I updated the focus to be much more visible.
The users also pointed out that it was difficult/impossible to use the control toggles as they aren't coded accessibly by Storybook and therefore the labels don't get read aloud properly. After testing Storybook's radio buttons, I realized that those weren't coded properly either. Because of the poor accessibility of toggles and radio buttons within Storybook, I switched all toggles and radio buttons in our stories to use selects as this seems to be the only accessible option available.
> Improve storybook a11y

- packages/react/tsconfig.json
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/stencil.config.ts
Update stencil to `v4.7.2` and the update and remove some configuration properties in `stencil.config.ts`.
- Added `validatePrimaryPackageOutputTarget` to validate package on build
- Remove `buildEs5` as it was causing issues with some frameworks
- Updated `experimentalImportInjection` to `enableImportInjection` as it is no longer experimental
- Removed `"sourceMaps": true` from `tsconfig` in react package to hopefully stop warnings when using components in `create-react-app`. This will also decrease the package size.
> Update stencil configuration for better build

- packages/web/src/components/gcds-alert/gcds-alert.css
- packages/web/src/components/gcds-button/gcds-button.css
- packages/web/src/components/gcds-card/gcds-card.css
- packages/web/src/components/gcds-container/gcds-container.css
- packages/web/src/components/gcds-details/gcds-details.css
- packages/web/src/components/gcds-footer/gcds-footer.css
- packages/web/src/components/gcds-header/gcds-header.css
- packages/web/src/components/gcds-heading/gcds-heading.css
- packages/web/src/components/gcds-lang-toggle/gcds-lang-toggle.css
- packages/web/src/components/gcds-nav-link/gcds-nav-link.css
- packages/web/src/components/gcds-phase-banner/gcds-phase-banner.css
- packages/web/src/components/gcds-select/gcds-select.css
- packages/web/src/components/gcds-sr-only/gcds-sr-only.css
- packages/web/src/components/gcds-text/gcds-text.css
We added slot styles a few weeks ago to fix a Chrome bug that kept the accessibility tree from populating properly. Setting the slot style to `inherit` was causing some issues with links not displaying the underline in a few places. Changing the slot styles to `initial` to prevent that issue.
The linter also added a few formatting updates :)
> fix: change slot styles to initial

- packages/web/README.md
Update web components package readme to use the correct instructions for Font awesome.
> fix: update font awesome instructions in readme

- packages/angular/src/lib/stencil-generated/components.ts
- packages/web/.storybook/preview-head.html
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-link/gcds-link.css
- packages/web/src/components/gcds-link/gcds-link.tsx
- packages/web/src/components/gcds-link/readme.md
- packages/web/src/components/gcds-link/stories/gcds-link.stories.js
- packages/web/src/components/gcds-link/stories/overview.mdx
- packages/web/src/components/gcds-link/test/gcds-link.spec.ts
- packages/web/src/index.html
As discussed in dev-design-sync recently, adding a new `link-variant` prop that allows users to use `light` links.
> feat: add light link-variant to link component

- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.tsx
Fix issue where the `gcds-file-uploader` would prevent form submission and display an error after choosing a file when validating `onBlur`. Added a small timeout to the validation in `handleChange` function to allow the file-uploader component to re-render with the submitted file.
> fix: File-uploader not validating properly

- packages/angular/package-lock.json
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-grid/gcds-grid.tsx
Export `ContentValues` type in `gcds-grid` to fix angular build. Was previously saying it could not find `ContentValues`.
> Export ContentValues type in gcds-grid to fix angular build

- renovate.json
Switching Renovate to use `main` as the base branch instead of `develop` since we will be removing the `develop` branch very soon.
> fix: update renovate base branch

- packages/ssr/lib/client/index.ts
- packages/ssr/scripts/utils.ts
When using the experimental SSR package, a hydration error would occur when a GCDS component was slotted into another GCDS component. This was happening since the `GcdsWrapper` wraps each  GCDS component when used causing conflicts in the render.  This can be seen with the breadcrumbs, top-nav and side-nav components using https://github.com/ethanWallace/components-ssr-test.
Added logic to add a `wrapped` prop into the rendering to prevent a `GcdsWrapper` from being placed inside another `GcdsWrapper`. The new prop is eventually removed before final render so it doesn't display on the component. These props should only be passed to GCDS components and avoid any other component.
> Add wrapped prop for conditional render to fix slot hydration issue

- .github/workflows/build-components.yml
Repurpose our old action to check failing builds on renovate PRs and make them available for all new PRs
Resolves https://github.com/cds-snc/design-gc-conception/issues/656
- https://github.com/cds-snc/design-gc-conception/issues/656
> ci: repurpose build action

- packages/web/src/components/gcds-link/gcds-link.tsx
Add additional check for `href` property to solve error warning in Next.js. The error would always seem to occur event when an `href` value was present.
> Add additional check for href property in gcds-link

- packages/web/src/components/gcds-nav-group/gcds-nav-group.tsx
- packages/web/src/components/gcds-top-nav/gcds-top-nav.tsx
To fix issue flagged in #383, moved the logic to close a dropwdown on focusout from the `gcds-top-nav` to `gcds-nav-group` to allow closure of singular dropdowns.
Resolves #383.
```html
<gcds-top-nav label="topbar" alignment="right" lang="en">
<gcds-nav-link href="#red" slot="home">Home</gcds-nav-link>
<gcds-nav-group
menu-label="Contact us submenu"
open-trigger="Contact us"
>
<gcds-nav-link href="#red">Form</gcds-nav-link>
<gcds-nav-link href="#red">GitHub</gcds-nav-link>
<gcds-nav-link href="#red">Slack</gcds-nav-link>
</gcds-nav-group>
<gcds-nav-link href="#red">Installation</gcds-nav-link>
<gcds-nav-link href="#red">Foundations</gcds-nav-link>
<gcds-nav-link href="#red" current>Components</gcds-nav-link>
<gcds-nav-group
menu-label="Contact us submenu"
open-trigger="Contact us"
> …
```
> Move toggle navigation focusout logic form top-nav to nav-group

- packages/web/src/components/gcds-textarea/gcds-textarea.css
- packages/web/src/components/gcds-textarea/gcds-textarea.tsx
- packages/web/src/components/gcds-textarea/test/gcds-textarea.spec.ts
CSS rewrite for the textarea component to add new CSS features like layers, etc.
> refactor: css rewrite textarea

- packages/web/src/components/gcds-hint/gcds-hint.css
- packages/web/src/components/gcds-hint/gcds-hint.tsx
- packages/web/src/components/gcds-hint/test/gcds-hint.spec.ts
CSS rewrite for the hint component to add new CSS features like layers, etc.
> refactor: css rewrite hint

- packages/web/src/components/gcds-error-message/gcds-error-message.css
CSS rewrite for the error message component to add new CSS features like layers, etc.
> refactor: css rewrite error message

- packages/web/src/components/gcds-checkbox/gcds-checkbox.css
CSS rewrite for the checkbox component to add new CSS features like layers, etc.
> refactor: css rewrite checkbox

- packages/web/src/components/gcds-input/gcds-input.css
CSS rewrite for the input component to add new CSS features like layers, etc.
> refactor: css rewrite input

- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs-item.css
- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs.css
CSS rewrite for the breadcrumbs component to add new CSS features like layers, etc.
> refactor: css rewrite breadcrumbs

- packages/web/.storybook/preview-head.html
A recent Storybook update changed the class name for one of our styles. I updated it to add the styling to a different (semantic) class in the preview code which Storybook normally doesn't update. If they change it again, I will change it to use the tag, but normally they do stick to their semantic class names.
Before:
After:
> fix: storybook spacing in component preview

- README.md
Updating the installation instructions in the repo's main README to reflect the changes for the mono repo setup.
Translations provided by @EliseKa (big thank you!)
To preview, you can visit https://github.com/cds-snc/gcds-components/tree/docs/monorepo-instructions and scroll down to see how it looks like.
> docs: Update installation instructions for the monorepo changes

- .github/workflows/release-generator.yml
I had the release please workflow paused and it didn't run, and realized it can't be manually dispatched.
This PR adds the `workflow_dispath` trigger to release please so we can choose to run it manually if we need to.
> ci: add workflow dispatch to release generator gh action

- .github/workflows/release-generator.yml
- release-please-config.json
GH Action for release please behaves differently from testing on local environment. I'll test the workflow on this PR instead to get a better view of what it's trying to do.
Things changed:
- The Release Please GH Action changed a few things (which we want!), the biggest thing is that we had the setting `release-type: node` set which seemed innocuous but [it actually now stops release please from using the manifest file](https://github.com/google-github-actions/release-please-action?tab=readme-ov-file#upgrading-from-v3-to-v4)
- Release please config for `node-workspaces` plugin is needed to update the peer dependencies. I thought about taking it out because it shows up as additional lines in the generated CHANGELOG, but without it, the PR fails due to the peer dependencies not being …
> ci: workflow fixes

- packages/web/src/components.d.ts
- packages/web/src/components/gcds-card/gcds-card.tsx
- packages/web/src/components/gcds-card/i18n/i18n.js
- packages/web/src/components/gcds-card/readme.md
- packages/web/src/components/gcds-card/test/gcds-card.spec.tsx
- packages/web/src/components/gcds-footer/gcds-footer.tsx
- packages/web/src/components/gcds-footer/test/gcds-footer.spec.tsx
- packages/web/src/components/gcds-input/gcds-input.tsx
- packages/web/src/components/gcds-input/readme.md
Updates to the `gcds-card`, `gcds-footer` and `gcds-input` components based on the OCADU report.
- https://github.com/cds-snc/design-gc-conception/issues/684 Add hidden "Tagged:" text to card tag
- Use `aria-describedby` to make sure tag is not missed if tabbing between focusable elements
- Remove `aria-label`'s and use existing headings in `gcds-footer` to label landmarks with `aria-labelledby`
- Change `autocomplete` property from `on  | off` to accept any `string`
> fix: Fixes identified in OCADU report (a11y and usability)

- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs-item.css
- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs-item.tsx
- packages/web/src/components/gcds-breadcrumbs/readme.md
- packages/web/src/components/gcds-card/gcds-card.css
- packages/web/src/components/gcds-card/gcds-card.tsx
- packages/web/src/components/gcds-card/readme.md
- packages/web/src/components/gcds-card/test/gcds-card.spec.tsx
- packages/web/src/components/gcds-footer/gcds-footer.css
- packages/web/src/components/gcds-footer/gcds-footer.tsx
- packages/web/src/components/gcds-footer/readme.md
- packages/web/src/components/gcds-footer/test/gcds-footer.spec.tsx
- packages/web/src/components/gcds-header/readme.md
- packages/web/src/components/gcds-lang-toggle/gcds-lang-toggle.css
- packages/web/src/components/gcds-lang-toggle/gcds-lang-toggle.tsx
- packages/web/src/components/gcds-lang-toggle/readme.md
- packages/web/src/components/gcds-lang-toggle/test/gcds-lang-toggle.spec.tsx
- packages/web/src/components/gcds-link/readme.md
Integrate `gcds-link` component into existing components to reduce code duplication created through repeated link styles.
`gcds-link` was integrated into:
- gcds-lang-toggle
- gcds-card
- gcds-breadcrumbs
- gcds-footer
The `gcds-link` component will not be integrated into the following components:
- Details - the link should remain a button for better accessibility.
- Nav link - nav-link has lots of additional functionality as well as custom styles, it makes more sense to not add `gcds-link` here
- Theme and topic menu - the links are populated by a fetch call from [canada.ca](https://www.google.com/url?q=http://canada.ca&sa=D&source=docs&ust=1708633836466739&usg=AOvVaw3UdzPPjd_0Fw66MqTmSMGi) so we aren't able to directly modify them
[Token …
> refactor: integrate gcds-link into existing components

- packages/web/src/components/gcds-search/gcds-search.tsx
- packages/web/src/components/gcds-search/test/gcds-search.spec.tsx
- packages/web/src/components/gcds-signature/gcds-signature.css
- packages/web/src/components/gcds-signature/gcds-signature.tsx
- packages/web/src/components/gcds-signature/test/gcds-signature.spec.tsx
Convert `gcds-search` and `gcds-signature` to use shadow-dom to help with rendering in a SSR environment.
> refactor: convert final components to use shadow-dom (gcds-search, gcds-signature)

- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs-item.tsx
- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs.css
- packages/web/src/components/gcds-button/readme.md
- packages/web/src/components/gcds-card/readme.md
- packages/web/src/components/gcds-card/test/gcds-card.spec.tsx
- packages/web/src/components/gcds-error-summary/gcds-error-summary.css
- packages/web/src/components/gcds-error-summary/gcds-error-summary.tsx
- packages/web/src/components/gcds-error-summary/readme.md
- packages/web/src/components/gcds-error-summary/test/gcds-error-summary.spec.tsx
- packages/web/src/components/gcds-footer/gcds-footer.tsx
- packages/web/src/components/gcds-footer/test/gcds-footer.spec.tsx
- packages/web/src/components/gcds-header/gcds-header.css
- packages/web/src/components/gcds-header/gcds-header.tsx
- packages/web/src/components/gcds-header/readme.md
- packages/web/src/components/gcds-header/test/gcds-header.spec.tsx
- packages/web/src/components/gcds-heading/readme.md
- packages/web/src/components/gcds-input/readme.md
- packages/web/src/components/gcds-lang-toggle/gcds-lang-toggle.css
- packages/web/src/components/gcds-lang-toggle/gcds-lang-toggle.tsx
- packages/web/src/components/gcds-lang-toggle/test/gcds-lang-toggle.spec.tsx
- packages/web/src/components/gcds-link/readme.md
- packages/web/src/components/gcds-sr-only/readme.md
- packages/web/src/components/gcds-stepper/gcds-stepper.css
- packages/web/src/components/gcds-stepper/gcds-stepper.tsx
- packages/web/src/components/gcds-stepper/readme.md
- packages/web/src/components/gcds-stepper/test/gcds-stepper.spec.tsx
Integrate `gcds-heading` component into existing components to reduce code duplication created through repeated heading styles.
`gcds-heading` was integrated into:
- gcds-error-summary
- gcds-stepper
Also added the correct size prop to the `gcds-link` component in our existing components to ensure proper font-sizes and reduce the used font tokens.
[Tokens PR](https://github.com/cds-snc/gcds-tokens/pull/235)
> refactor: integrate gcds-heading into existing components

- packages/react/tsconfig.json
- Fixes #466
Tested with a small create react app with typescript. I saw the exact same message as detailed in #466, and tested this updated package on that app. This fix should resolve the issue; I don't see anymore typescript errors during testing.
> fix: invalid path for types

- packages/web/src/components.d.ts
- packages/web/src/components/gcds-grid/gcds-grid.tsx
- packages/web/src/components/gcds-grid/stories/gcds-grid.stories.tsx
- packages/web/src/components/gcds-grid/stories/overview.mdx
- packages/web/src/components/gcds-grid/test/gcds-grid.spec.ts
Limiting the allowed values for the grid tag property after some feedback we received from the OCADU report.
Linked to
- https://github.com/cds-snc/design-gc-conception/issues/757
> feat: set allowed values for grid tag property to limit misuse

- packages/ssr/lib/client/index.ts
- packages/ssr/lib/client/render.ts
- packages/web/stencil.config.ts
Prevent errors from appearing in Chrome by adjusting render logic.
- Added a list of our components that are form-associated to add `shadowrootdelegatesfocus` to template tag in DSD
- Fixed render function from attaching multiple template tags to custom elements in components
> fix: Declarative shadow-dom error in Chrome

- packages/ssr/lib/utils.ts
- packages/web/src/components/gcds-nav-group/gcds-nav-group.css
- packages/web/src/components/gcds-nav-group/gcds-nav-group.tsx
- packages/web/src/components/gcds-nav-group/test/gcds-nav-group.spec.tsx
- packages/web/src/components/gcds-nav-link/gcds-nav-link.css
- packages/web/src/components/gcds-nav-link/gcds-nav-link.tsx
- packages/web/src/components/gcds-nav-link/test/gcds-nav-link.spec.tsx
- packages/web/src/components/gcds-side-nav/gcds-side-nav.css
- packages/web/src/components/gcds-side-nav/gcds-side-nav.tsx
- packages/web/src/components/gcds-side-nav/test/gcds-side-nav.spec.tsx
- packages/web/src/components/gcds-top-nav/gcds-top-nav.tsx
- packages/web/src/components/gcds-top-nav/test/gcds-top-nav.spec.tsx
As identified in https://github.com/cds-snc/design-gc-conception/issues/756 using `role="menu"` may cause issues with some assistive technologies. Removed use of menu roles from `gcds-top-nav`, `gcds-side-nav`, `gcds-nav-group` and `gcds-nav-link`.
Also removed/moved some classes that are used for styling off of the host elements of `gcds-nav-group` and `gcds-nav-link` to prevent hydration errors when used in SSR environment.
> rework: Rework navigation components to remove menu role and hydration issues

- packages/ssr/lib/client/render.ts
Missed a use case when applying fix from before. Render function should now be able to handle a component that has more than one of the same custom elements in it's shadow root (ex: `gcds-link` in `gcds-footer`). Also adds the required `shadowrootdelegatesfocus` attribute to the `template` element if custom element is `delegateFocus:true`.
> fix: Update render function to handle more than one custom element

- packages/ssr/package-lock.json
- packages/ssr/package.json
Rename `@cdssnc/gcds-components-ssr` to `@cdssnc/gcds-components-react-ssr` for better understanding of what environment to use the package in.
> chore: rename SSR package to more specific name

- packages/ssr/package.json
Importing css in my react file like
```javascript
import "@cdssnc/gcds-components-react-ssr/gcds.css";
```
gives me the following error:
`Module not found: Package path ./gcds.css is not exported from package <path>/@cdssnc/gcds-components-react-ssr (see exports field in node_modules/@cdssnc/gcds-components-react-ssr/package.json)`
This PR fixes the issue
> fix: package path not found for gcds.css

- packages/web/src/utils/utils.ts
Update the `assignLanguage` and `inheritAttributes` to be more usable and functional with GC Design System components going forward.
Previously the `assignLanguage` would check if a `lang` attribute has been assigned to the host element of a component if needed. If not found, the function would then check the document element to get the page language for the component.
To better match how `lang` works in HTML, the component will now check it's ancestors all the way up to the document element for a `lang` attribute. This allows developers to tag sections of a page a different language from the default page language and have the component inherit the correct language.
`inheritAttributes` was built to take data attributes assigned to form components and pass them down to the input rendered …
> fix: Update utility functions for more usability

- package.json
Makes it easer to `npm run start` from the root of the folder
> chore: add run script

- packages/web/src/components/gcds-card/gcds-card.css
Removed CSS from `<gcds-card type="link">` that caused the card title link text to display as the same colour as the background producing an accessibility error when the card was focused and hovered at the same time.
> fix: Remove CSS causing card title text to disappear on hover/focus

- packages/angular/src/lib/stencil-generated/components.ts
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-checkbox/gcds-checkbox.tsx
- packages/web/src/components/gcds-checkbox/test/gcds-checkbox.spec.tsx
- packages/web/src/components/gcds-error-message/gcds-error-message.css
- packages/web/src/components/gcds-error-message/gcds-error-message.tsx
- packages/web/src/components/gcds-error-message/readme.md
- packages/web/src/components/gcds-error-message/stories/gcds-error-message.stories.tsx
- packages/web/src/components/gcds-error-message/test/gcds-error-message.spec.ts
- packages/web/src/components/gcds-fieldset/gcds-fieldset.tsx
- packages/web/src/components/gcds-fieldset/test/gcds-fieldset.spec.tsx
- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.tsx
- packages/web/src/components/gcds-file-uploader/test/gcds-file-uploader.spec.tsx
- packages/web/src/components/gcds-hint/gcds-hint.css
- packages/web/src/components/gcds-hint/gcds-hint.tsx
- packages/web/src/components/gcds-hint/readme.md
- packages/web/src/components/gcds-hint/test/gcds-hint.spec.ts
- packages/web/src/components/gcds-input/gcds-input.tsx
- packages/web/src/components/gcds-input/test/gcds-input.spec.ts
- packages/web/src/components/gcds-radio-group/gcds-radio-group.tsx
- packages/web/src/components/gcds-radio-group/test/gcds-radio-group.spec.tsx
- packages/web/src/components/gcds-select/gcds-select.tsx
- packages/web/src/components/gcds-select/test/gcds-select.spec.tsx
- packages/web/src/components/gcds-textarea/gcds-textarea.tsx
- packages/web/src/components/gcds-textarea/test/gcds-textarea.spec.ts
As discussed in dev sync:
- Change gcds-error-message to use slot instead of message prop
- Change gcds-hint to use slot instead of hint prop
> refactor: change gcds-error-message and gcds-hint to use slot instead of prop

- packages/angular/src/lib/stencil-generated/components.ts
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-alert/gcds-alert.tsx
- packages/web/src/components/gcds-alert/readme.md
- packages/web/src/components/gcds-button/gcds-button.tsx
- packages/web/src/components/gcds-button/readme.md
- packages/web/src/components/gcds-checkbox/gcds-checkbox.tsx
- packages/web/src/components/gcds-checkbox/readme.md
- packages/web/src/components/gcds-details/gcds-details.tsx
- packages/web/src/components/gcds-details/readme.md
- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.tsx
- packages/web/src/components/gcds-file-uploader/readme.md
- packages/web/src/components/gcds-hint/readme.md
- packages/web/src/components/gcds-input/gcds-input.tsx
- packages/web/src/components/gcds-input/readme.md
- packages/web/src/components/gcds-link/gcds-link.tsx
- packages/web/src/components/gcds-nav-group/gcds-nav-group.tsx
- packages/web/src/components/gcds-nav-group/readme.md
- packages/web/src/components/gcds-nav-link/gcds-nav-link.tsx
- packages/web/src/components/gcds-pagination/gcds-pagination.tsx
- packages/web/src/components/gcds-pagination/readme.md
- packages/web/src/components/gcds-radio-group/gcds-radio-group.tsx
- packages/web/src/components/gcds-radio-group/readme.md
- packages/web/src/components/gcds-search/gcds-search.tsx
- packages/web/src/components/gcds-search/readme.md
- packages/web/src/components/gcds-select/gcds-select.tsx
- packages/web/src/components/gcds-select/readme.md
- packages/web/src/components/gcds-textarea/gcds-textarea.tsx
- packages/web/src/components/gcds-textarea/readme.md
- packages/web/src/utils/utils.ts
Went through the interactive components to make sure event naming and firing(emitting) behaviour was consistent between components. Also created a `emitEvent` utility function that will properly cancel cancelled events if either the gcds custom event or the native HTML event has been prevented.
``` js
// Emit event with logic to cancel HTML events
// Returns false if event has been prevented
export const emitEvent = (
e: Event,
customEvent: EventEmitter,
value?: unknown,
) => {
const event = customEvent.emit(value);
// Was the custom or native event interrupted
if (event.defaultPrevented || e.defaultPrevented) {
// Stop native HTML event in shadow-dom
e.preventDefault();
return false;
}
return true;
};
```
The `emitEvent` function allows the developer to cancel either the native HTML …
> feat: consistent component events

- .github/ISSUE_TEMPLATE/contributions.yml
This adds a template to let users submit contributions
Fixes:
- https://github.com/cds-snc/design-gc-conception/issues/709
More info in this [google doc (section next priorities)](https://docs.google.com/document/d/1UPjV8DQkvb8a40-BulgPJbwmv6z_64cx06QnqI1qL5c/edit)
> docs: add new contributions template for new issues

- packages/angular/src/lib/stencil-generated/components.ts
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.tsx
- packages/web/src/components/gcds-input/gcds-input.tsx
- packages/web/src/components/gcds-search/gcds-search.tsx
- packages/web/src/components/gcds-search/readme.md
- packages/web/src/components/gcds-select/gcds-select.tsx
- packages/web/src/components/gcds-textarea/gcds-textarea.tsx
Noticed with recent event refactor the `gcdsChange` event wasn't actually being emitted, the `gcdsInput` event was being emitted on the `onChange` event.
> fix: emit proper events onChange

- packages/web/src/components/gcds-error-summary/gcds-error-summary.css
Revert style changes to error summary:
- Links are red with our regular focus state for links
- Border is red
- Focus does not focus border
- Remove focus text colour from heading when component is in focus
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/899)
> refactor: revert style changes to error summary

- packages/web/src/components/gcds-radio-group/stories/gcds-radio-group.stories.tsx
Add prop template to render events and properties for `gcds-radio-group` in storybook.
> chore(storybook): Add prop template to gcds-radio-group

- packages/web/src/components/gcds-checkbox/gcds-checkbox.tsx
- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.tsx
- packages/web/src/components/gcds-input/gcds-input.tsx
- packages/web/src/components/gcds-radio-group/gcds-radio-group.tsx
- packages/web/src/components/gcds-select/gcds-select.tsx
- packages/web/src/components/gcds-textarea/gcds-textarea.tsx
To make sure developers have access to both native HTML events and our custom events, I put in some logic that will emit the `change` event again to get passed the shadow-dom.
> fix: Emit change event from form components

- .gitignore
- packages/web/package.json
- packages/web/stencil.config.ts
Add the `dist-hydrate-script` output to web components package. This will allow developers the tools to be able to render the Stencil web components on the server side in different frameworks available from `@cdssnc/gcds-components/hydrate`.
> feat: Add dist-hyrdate-app output

- .github/workflows/compile-and-publish.yml
To follow process of the web component package, add a sleep command to the CDN publish of the other packages.
> chore: Add sleep to CDN publish of angular, react and vue packages

- packages/web/src/components/gcds-input/gcds-input.tsx
Update input component:
-  Increase input width calculation (2x)
-  Remove maxLength
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/801)
> refactor: update input component to increase input width calculation

- packages/web/src/components/gcds-sr-only/gcds-sr-only.css
The French theme and topic menu button was split into two lines because the host element of the screenreader-only component was set to `display: block;`. Fixed it and it should display on one line now, like the EN menu button.
[Bug report](https://github.com/cds-snc/gcds-components/issues/534)
> fix: misaligned of FR theme and topic menu button (bug)

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/contributions.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Updates the issue templates for bug reports and contribution templates
[Translation docs here](https://docs.google.com/document/d/1nqGUV0p8PLAj63qW7O2V5qJfo0hChfKdQUtjieoJhB0/edit)
Updates:
- https://github.com/cds-snc/design-gc-conception/issues/709
The description appears at the top. The "If this doesn't look right, [choose a different type.](https://github.com/daine/issue_tests/issues/new/choose)" portion is added on by github, not us. I tried to add:
> Si ce n’est pas ce que vous souhaitez faire, [choisissez un autre formulaire](https://github.com/cds-snc/gcds-components/issues/new/choose).
but it doesn't look great because it also gets added on the "Choose issue type page", and the link doesn't show up as well on both pages because it doesn't accept markdown format on that field …
> docs: add fr translation for issue templates (contribution, feature request and bug report)

- packages/web/.storybook/preview-head.html
- packages/web/src/components/gcds-button/stories/gcds-button.stories.js
Adding custom copy code buttons to our Storybook code preview - one for the web component code and one for the React component code. Users are never going to need to copy both web and React, this gives them the option to choose.
I looked into separating the web components and React code preview into two. It would involve having 2 separate iframes with two separate property tables for which we would have to display tabs (or something similar) on the live demo section on our code page. We could look into doing that when we redesign the site, but it seems out of scope as a quick fix since it would require writing new stories for all components, design input, etc.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/862 …
> chore(storybook): add custom copy code button to storybook code preview

- packages/web/.storybook/preview-head.html
On the events and properties page, stop the web component and react copy buttons from rendering another time when modifying properties.
**Note**: This solution only works for the events and properties page and is a little hacky on top of our hacky JS. Will solve the other issues in another PR, just wanted to get the user facing issue fixed first.
> chore(storybook): Stop copy buttons rendering more than once 

- package-lock.json
- packages/web/.storybook/preview-head.html
- packages/web/src/components/gcds-breadcrumbs/stories/gcds-breadcrumbs.stories.tsx
- packages/web/src/components/gcds-button/stories/gcds-button.stories.js
- packages/web/src/components/gcds-card/stories/gcds-card.stories.tsx
- packages/web/src/components/gcds-container/stories/gcds-container.stories.tsx
- packages/web/src/components/gcds-date-modified/stories/gcds-date-modified.stories.tsx
- packages/web/src/components/gcds-details/stories/gcds-details.stories.tsx
- packages/web/src/components/gcds-error-message/stories/gcds-error-message.stories.tsx
- packages/web/src/components/gcds-grid/stories/gcds-grid.stories.tsx
- packages/web/src/components/gcds-header/stories/gcds-header.stories.tsx
- packages/web/src/components/gcds-heading/stories/gcds-heading.stories.tsx
- packages/web/src/components/gcds-link/stories/gcds-link.stories.js
- packages/web/src/components/gcds-nav-link/stories/gcds-nav-link.stories.tsx
- packages/web/src/components/gcds-sr-only/stories/gcds-sr-only.stories.tsx
- packages/web/src/components/gcds-text/stories/gcds-text.stories.tsx
- packages/web/src/components/gcds-top-nav/stories/gcds-top-nav.stories.tsx
Adding descriptions to the slots in Storybook to make it easier to understand what to use them for.
What do you think about this @daine @ethanWallace ?
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/862)
> chore(storybook): add description to slots

- packages/web/.storybook/preview-head.html
Fix issue in storybook overview pages where the copy code buttons would disappear for all previews if the 'Hide code' button was toggled.
> chore(storybook): Fix display of overview copy buttons

- .github/workflows/compile-and-publish.yml
- .github/workflows/upload-cdn.yml
- utils/scripts/upload_to_cdn.sh
Refactor: separate the CDN upload process and add a retry to wait for npm publishing to complete 
_Fix for:_
- https://github.com/cds-snc/design-gc-conception/issues/907
This adds a `retry` functionality to the part where the files get uploaded to the CDN. The script usually fails if the package is not yet available on NPM, especially if it's a new package.
This separates the CDN upload part in a script called `upload_to_cdn.sh`, which runs on **new** the GitHub workflow file `upload-cdn.yml`.
- The workflow action runs after the `compile-and-publish.yml` workflow is completed.
- We can run it manually if we need to -- you can run it multiple times because it just updates the files based on the NPM version of the specified package.
I ran our [terraform …
> refactor: separate the CDN upload process and add a retry script

- .github/workflows/upload-cdn.yml
This is an update to the previous PR #563:
- #563 
To make sure the `github.event.workflow_run.conclusion` check doesn't fail, add an additional check that the event name is `workflow_run`.
I tested this gh action on my own repo
- ✅ [Run is triggered by a workflow (publish packages)](https://github.com/daine/gcds-components/actions/runs/9589823863)
- ✅ [Run is triggered manually (workflow_dispatch)](https://github.com/daine/gcds-components/actions/runs/9589902265)
Both ran successfully
> refactor: update logic check on when to run upload-to-cdn

- packages/angular/src/lib/stencil-generated/angular-component-lib/utils.ts
- packages/angular/src/lib/stencil-generated/components.ts
- utils/angular-output-target/__tests__/generate-angular-component.spec.ts
- utils/angular-output-target/angular-component-lib/utils.ts
- utils/angular-output-target/src/generate-angular-component.ts
With the `v0.22.0` release of the `@cdssnc/gcds-components-angular`, `@Outputs` were added to the generated angular components. Unfortunately this was now causing custom events like `gcdsClick` to be emitted twice.
To fix, I removed Stencil's implementation of events from `rxjs` to remove the duplicate emitted events.
```
import {Component} from '@angular/core';
@Component({
selector: 'app-click-me-gcds',
template: ` <gcds-button type="button" (gcdsClick)="onClickMe()">Click me!</gcds-button>
<gcds-pagination type="list" current-page="3" total-pages="20" (gcdsClick)="onClick($event)"></gcds-pagination>
`,
})
export class ClickMeGcdsComponent {
clickMessage = '';
onClickMe() {
console.log('clicked')
}
onClick(event: any) {
event.preventDefault();
console.log(event.detail)
}
}
``` …
> fix: Remove rxjs events to avoid duplicate custom events in Angular

- packages/react-ssr/package.json
Removes post install on the package.json
This fixes the issue of the install command failing to complete
> fix: remove post install on react ssr package

- packages/web/src/components/gcds-details/gcds-details.css
- packages/web/src/components/gcds-link/gcds-link.css
- packages/web/src/components/gcds-nav-group/gcds-nav-group.tsx
- packages/web/src/components/gcds-nav-link/gcds-nav-link.css
- packages/web/src/index.html
FIx a couple issues related to how Safari renders and handles focus.
Safari does not accept the `text-decoration` shorthand so switched to using all properties.
Safari handles focus a little differently from other browsers so the dropdown logic logic would fire before the `nav-link` click event could be called. Added a small timeout to the `focusout` listener function to allow the `gcds-nav-link` click to go through.
> fix: Safari a11y issues with links and nav group focus

- package.json
- packages/web/package.json
Lerna has been causing an issue with build order by not building the packages in the correct order. Switch the main build script to use npm workspace build instead of Lerna to build in the proper order.
> build: Remove lerna and use npm workspace in build script

- release-please-config.json
Release please creates a different version for the react-ssr package, hopefully if we add it to the linked versions it'll be on the same version too.
> ci: add react-ssr to release please grouping

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs-item.css
- packages/web/src/components/gcds-date-modified/gcds-date-modified.tsx
- packages/web/src/components/gcds-date-modified/i18n/i18n.js
- packages/web/src/components/gcds-details/gcds-details.css
- packages/web/src/components/gcds-error-message/stories/gcds-error-message.stories.tsx
- packages/web/src/components/gcds-label/gcds-label.css
- packages/web/src/components/gcds-side-nav/gcds-side-nav.tsx
- packages/web/src/components/gcds-side-nav/i18n/i18n.js
- packages/web/src/components/gcds-top-nav/gcds-top-nav.tsx
- packages/web/src/components/gcds-top-nav/i18n/i18n.js
Update small design misalignments in various components:
- Update Storybook error message text to match docs site
- Move integrated content for date-modified, side-nav, and top-nav components into their i18n files
- Update required label to use regular font weight
- Style breadcrumbs as list for smaller screens
- Always left-align button text in details summary
> fix: update small design misalignments in various components

- packages/web/src/components/gcds-fieldset/gcds-fieldset.tsx
- packages/web/src/components/gcds-fieldset/test/gcds-fieldset.spec.tsx
Teeny tiny PR to update the fieldset legend required from a `strong` tag to a `span` tag since it won't be bold moving forward anymore.
> fix: change fieldset legend required to span

- release-please-config.json
Current release-please configuration marks all packages as prerelease, this will hopefully stop that form happening.
> build: Remove prerelease tag from packages

- .github/workflows/compile-and-publish.yml
To solve [issue](https://github.com/cds-snc/design-gc-conception/issues/1084) of `@cdssnc/gcds-components-react-ssr` not being tagged as latest on npm, add `react-ssr` to publishing step that publishes all framework packages. This will reduce duplication of code and tag the release as latest.
> build: Include react-ssr in normal publish workflow

- packages/angular/src/lib/stencil-generated/components.ts
- packages/vue/lib/components.ts
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-button/gcds-button.tsx
- packages/web/src/components/gcds-button/readme.md
- packages/web/src/components/gcds-button/stories/gcds-button.stories.js
On user request: Add `value` attribute to `gcds-button`.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1109)
> feat: add value attribute to gcds-button

- packages/react-ssr/scripts/build.ts
- utils/angular-output-target/__tests__/generate-value-accessors.spec.ts
This fixes the installation and build scripts when executed directly on the MS Windows operating system.
1. Clone the repository on a Windows workstation where only NodeJS 18/20 is installed.
2. run `npm install`:
* **Without** the fix: The installation build stops during the test execution of `generate-value-accessors.spec.ts``.
* **With** the fix: The installation will proceed and successfully finish as expected.
3. run `npm run build`:
* **Without** the fix: The build fails for `react-ssr`, stating that local file systems imported starting with `c:/` must be prefixed with the `file://` URI scheme.
* **With** the fix: The build will proceed and successfully finish as expected.
With this proposed fix, I was able to successfully use Node 20 for my setup on my MS Windows computer and also …
> build: Fix npm build on MS window native

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-search/gcds-search.css
Adds mobile font size to the Search component
Replaces default font size on the Search component with desktop (default) and mobile values
Fix for:
- https://github.com/cds-snc/design-gc-conception/issues/1134
~‼️ Needs tokens from https://github.com/cds-snc/gcds-tokens/pull/321~
Tokens are now added in the latest version `1.19.0`
> fix: add mobile font size to search component

- packages/web/src/components/gcds-sr-only/gcds-sr-only.css
- packages/web/src/components/gcds-sr-only/test/gcds-sr-only.e2e.ts
Align the style of `gcds-sr-only` with the [WCAG CSS technique C7](https://www.w3.org/WAI/WCAG22/Techniques/css/C7) and it avoid the 0 pixel technique because it is not recommended according to a [WebAim article about invisible content just for screen reader users](https://webaim.org/techniques/css/invisiblecontent/). 
It also remove the space taken by the component as it must be visually invisible but only visible to screen reader only.
The following tests were automated and integrated to the unit testing of the `<gcds-sr-only>` component
1. Put the `<gcds-sr-only>` component in between 2 other visually rendered component.
2. **Expected:** The bottom of the preceding component and the top of the next one should be the same without any space in between.
| Current | With this fix |
| …
> fix(gcds-sr-only): Align with WCAG technique C7

- packages/web/src/components/gcds-grid/gcds-grid-col.css
- packages/web/src/components/gcds-nav-link/gcds-nav-link.css
The `gcds-nav-link` has a typo when setting the font property (`var(---gcds-nav-link-font)`). It should be `var(--gcds-nav-link-font)`.
> fix: Fix typos in tokens

- packages/web/src/components/gcds-select/gcds-select.tsx
Add `mutationObserver` to `gcds-select` to observe if passed `<options>` have been changed. This allows the select component to keep the same behaviour as the HTML select.
[Example of issue using React](https://stackblitz.com/edit/vitejs-vite-rldmhu?file=src%2FApp.tsx)
https://github.com/cds-snc/gcds-components/issues/643
> fix: Update available options in select if changed

- packages/web/src/components/gcds-container/stories/gcds-container.stories.tsx
Fix typo in `gcds-container` properties in storybook. The `main-container` attribute was appearing as `mainContainer`.
> docs: Fix typo with main-container attribute in storybook

- packages/web/src/components/gcds-error-summary/gcds-error-summary.tsx
As highlighted in https://github.com/cds-snc/gcds-components/issues/664, GC Design System form elements were not focusing when error links were clicked from manually entered list with `error-links` property. Modified logic to not call `scrollIntoView()` if no label is found, this logic is meant for non-gcds form elements.
> fix(gcds-error-summary): focusing gcds element from manual error-links list

- packages/web/.storybook/preview-head.html
Add some logic to add a `min-height` to storybook frame to hopefully prevent large flashes when component re-renders. Seen when viewing components through the iframe view (`/iframe.html?viewMode=docs&demo=true&singleStory=true&id=components-input--events-properties&lang=en`).
> chore: Add logic to prevent flash on prop change in storybook

- packages/web/src/components/gcds-button/stories/gcds-button.stories.js
- packages/web/src/components/gcds-card/stories/gcds-card.stories.tsx
- packages/web/src/components/gcds-checkbox/stories/gcds-checkbox.stories.tsx
- packages/web/src/components/gcds-date-input/stories/gcds-date-input.stories.tsx
- packages/web/src/components/gcds-fieldset/stories/gcds-fieldset.stories.tsx
- packages/web/src/components/gcds-file-uploader/stories/gcds-file-uploader.stories.tsx
- packages/web/src/components/gcds-input/stories/gcds-input.stories.tsx
- packages/web/src/components/gcds-radio-group/stories/gcds-radio-group.stories.tsx
- packages/web/src/components/gcds-select/stories/gcds-select.stories.tsx
- packages/web/src/components/gcds-textarea/stories/gcds-textarea.stories.tsx
- packages/web/src/utils/storybook/component-properties.js
As mentioned in https://github.com/cds-snc/gcds-components/issues/671, the events table of storybook will render a `Setup controls` link when the table row is hovered. This creates a reusable object to use for all event controls that will prevent the link from rendering.
> storybook: Remove setup controls link in event table

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-details/gcds-details.css
Adjust details tokens:
- Add tokens for desktop and mobile font sizes
- Adjust padding for summary and panel
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1147)
Note: The link component already uses the correct styles.
> refactor: adjust details font sizes and summary + panel padding

- packages/angular/src/lib/stencil-generated/components.ts
- packages/vue/lib/components.ts
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.tsx
- packages/web/src/components/gcds-file-uploader/readme.md
- packages/web/src/components/gcds-file-uploader/test/gcds-file-uploader.e2e.ts
To match how developers interact with the native HTML file input, add a `files` property to easily access uploaded files to file uploader.
With HTML file inputs, to access the files uploaded on a change event a developer would just need to use `event.target.files`. With `gcds-file-uploader` it requires using `event.target.shadowRoot.querySelector('input').files` to acheive the same functionality. Adding the `files` prop will allow developers to use the usual method to gain access to the files.
```html
<gcds-file-uploader
uploader-id="form-uploader"
label="Upload file"
id="file"
multiple
required
></gcds-file-uploader>
<script>
document.getElementById('file').addEventListener('change', (e) => {
// File-uploader files - new way
console.log(e.target.files);
// Input in shadow-dom files - old …
```
> feat(gcds-file-uploader): Add files prop for ease of access to uploaded files

- packages/web/src/components/gcds-date-modified/gcds-date-modified.tsx
- packages/web/src/components/gcds-date-modified/stories/gcds-date-modified.stories.tsx
- packages/web/src/components/gcds-date-modified/test/gcds-date-modified.spec.tsx
Prevent date-modified component from rendering when no children (date or version) are passed.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1127)
> refactor: improve date-modified validation

- packages/web/src/components/gcds-fieldset/gcds-fieldset.css
As mentioned in https://github.com/cds-snc/gcds-components/issues/682, elements in the `gcds-fieldset` would no longer be responsive and overflow with the viewport. The issue just mentions the `gcds-select` but further tests found this was also happening with the other form components (input, textarea, etc). Added `min-inline-size: auto` to the fieldset's CSS as recommended from the issue.
> fix(gcds-fieldset): Add CSS to allow form components to maintain responsive layout

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-checkbox/gcds-checkbox.css
- packages/web/src/components/gcds-fieldset/gcds-fieldset.css
- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.css
- packages/web/src/components/gcds-hint/gcds-hint.css
- packages/web/src/components/gcds-input/gcds-input.css
- packages/web/src/components/gcds-label/gcds-label.css
- packages/web/src/components/gcds-radio-group/gcds-radio-group.css
- packages/web/src/components/gcds-search/gcds-search.css
- packages/web/src/components/gcds-select/gcds-select.css
- packages/web/src/components/gcds-textarea/gcds-textarea.css
To align with the design specs in Figma, remove the focus colour from form component labels when a component is focused. Form component labels/legends should no longer change to the focus colour.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1118)
> refactor: remove focus colour from label, hint and legend

- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs-item.css
Fix breadcrumbs item arrow display, reported in [issue 705](https://github.com/cds-snc/gcds-components/issues/705).
Note:
After release, update issue!
> fix: breadcrumbs item arrow display

- package-lock.json
- packages/vue/tests/app/package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-error-message/gcds-error-message.tsx
- packages/web/src/components/gcds-error-message/test/gcds-error-message.spec.ts
Adjust spacing for some of our form elements to optimize design after our spacing update.
Note:
Wait for the [updated token package](https://github.com/cds-snc/gcds-tokens/pull/365) to release form spacing changes together.
> refactor: adjust form element spacing

- .github/workflows/run-tests.yml
Noticed the run-tests workflow was no longer working as it was failing trying to install dependencies for playwright.
GitHub has started transitioning the runner `ubuntu-latest` to use Ubuntu v24 instead of Ubuntu v22.04. Playwright has not been updated to work with the latest version of Ubuntu so we need to force using `v22.04` with our `run-tests` workflow.
> ci: pin workflow image to ubuntu 22

- packages/web/src/components/gcds-notice/gcds-notice.tsx
- packages/web/src/components/gcds-notice/i18n/i18n.js
- packages/web/src/components/gcds-notice/test/gcds-notice.spec.tsx
To better accommodate screen readers, add text only available to screen readers in the notice headings announcing the notice type.
> fix(gcds-notice): Add accessible labels to identify notice type

- packages/web/src/components/gcds-pagination/gcds-pagination.css
- packages/web/src/components/gcds-pagination/gcds-pagination.tsx
- packages/web/src/components/gcds-pagination/test/gcds-pagination.spec.tsx
As mentioned in https://github.com/cds-snc/gcds-components/issues/715, add `tabindex="0"` to links contained in the `gcds-pagination` component to allow events to fire and keyboard navigation.
Run these tests in a webkit browser like Safari.
1. On main branch run `npm run start`
2. Navigate to `http://localhost:3333/src` in Safari
3. Scroll down to pagination components
4. Click the links within pagination
5. Notice the url has not changed
6. Switch to this branch
7. Repeat steps 1 to 4 on this branch
8. Notice the url has updated to include the querystrings from pagination
> fix(gcds-pagination): Add tabindex="0" to <a> tags to function in webkit browsers

- packages/web/src/components.d.ts
- packages/web/src/components/gcds-input/gcds-input.tsx
- packages/web/src/components/gcds-input/readme.md
Update the input size description to explain more accurately what the property does.
Look at the [README description](https://github.com/cds-snc/gcds-components/tree/fix-gcds-input-size-description/packages/web/src/components/gcds-input) for the input size prop.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1206) for details.
> fix: input size property description

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-pagination/gcds-pagination.tsx
- packages/web/src/components/gcds-pagination/test/gcds-pagination.spec.tsx
Updating the component spacing for a few components to align with the design after the big typography and spacing update. Additionally, updating the arrows used in the pagination component to ensure they match the updated design. Here is an overview of the changes:
- Update error summary spacing
- Update nav group trigger
- Update stepper mobile margin
- Update pagination arrows to match the design
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1303)
> refactor: update component spacing + pagination arrows

- packages/web/src/components/gcds-textarea/gcds-textarea.tsx
As mentioned in https://github.com/cds-snc/gcds-components/issues/685, the `gcds-textarea` value would not be properly reset when using Formgroup. After some investigation it was revealed this wasn't directly related to the Angular implementation of `gcds-textarea` and was just a bug within the web component.
When the component's value changes, the value was not properly being transferred to the textarea in the shadow-root of the component so the shadow-root textarea would keep the previous value while the rest of the component would register the new value.
```html
<gcds-textarea
textarea-id="form-message"
label="Message"
hint="This is a hint."
character-count="400"
required
id="text"
></gcds-textarea>
<button type="button" onclick="resettextarea();">Reset textarea value</button>
<script> …
```
> fix(gcds-textarea): Properly set value in shadow-root textarea

- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs-item.css
To align with Canada.ca, the breadcrumbs should not stack (each breadcrumbs should not start on a new line).
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1270)
- Run `npm run start`
- Wait for the local test site to load, then reduce the browser window to mobile size.
- Result: the breadcrumbs shouldn't stack anymore.
> refactor: remove mobile stacking from breadcrumbs

- packages/web/src/components/gcds-link/gcds-link.css
While publishing new content for our site, I noticed our `gcds-link` component does not wrap around in paragraphs like a normal `<a>` tag. Update the reset style to `display: inline` to allow the `gcds-link` to wrap like a default HTML `a` tag.
Using the paragraph below, observe how the `gcds-link` wraps around the page while changing the viewport size.
```
<p>GC Design System is a service that is owned and operated by the Canadian Digital Service (CDS) at <gcds-link href="https://www.canada.ca/en/employment-social-development.html" external>Employment and Social Development Canada (ESDC).</gcds-link> This service enables Canadian federal departments and agencies to build and design trusted, predictable and accessible web and application experiences.</p>
```
> fix(gcds-link): Display property to allow normal link wrap behaviour

- packages/web/src/index.html
Updating the utility framework link in our demo page to use the correct, new link and set it to `@latest`.
> chore: update UF link in demo page

- packages/web/src/components/gcds-nav-group/gcds-nav-group.css
- packages/web/src/components/gcds-nav-group/gcds-nav-group.tsx
- packages/web/src/components/gcds-top-nav/gcds-top-nav.tsx
- packages/web/src/utils/menus/utils.ts
- packages/web/src/utils/utils.ts
Address multiple issues with the navigation components (`gcds-top-nav`, `gcds-nav-group` and `gcds-side-nav`) like using tab to navigate the `gcds-top-nav`, `gcds-side-nav` mobile menu display issue and mobile menu for both nav components not preventing pagescrolling.
As mentioned in https://github.com/cds-snc/gcds-components/issues/719 using `tab` would close dropdown/mobile menus, you are now able to fully navigate the `gcds-top-nav` using `tab`. When using `tab` in the mobile menus, the focus will stay within the menu until the user clicks the close button or hits `esc`. 
Using the navigation component below:
```html
<gcds-top-nav label="topbar" alignment="right" lang="en">
<gcds-nav-link href="#home" slot="home">Home</gcds-nav-link>
<gcds-nav-link …
```
> fix: nav component display and interaction issues

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-date-modified/gcds-date-modified.css
To match the requirements for the alignment of the mandatory elements, update the font size of the date-modified component to 16px.
Date-modified text uses font size of 16px for both desktop and mobile since it is a sub-component of the footer.
The [Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1266) for the requested change.
Do not merge until token package has been updated to include [this PR](https://github.com/cds-snc/gcds-tokens/pull/396).
> style: update date-modified font size

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-footer/gcds-footer.css
We are slightly adjusting the mobile padding for the footer bands and increasing the spacing between the links in the sub band to match the other link spacing.
Dependant on the next token release, including [this PR](https://github.com/cds-snc/gcds-tokens/pull/403).
> style: adjust mobile padding for footer bands

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-header/gcds-header.css
- packages/web/src/components/gcds-lang-toggle/gcds-lang-toggle.css
- packages/web/src/components/gcds-signature/gcds-signature.css
Updating the header spacing tokens as well as the header border colour and width to align with the new header design. This work is part of the alignment work for mandatory elements with DTO.
The Zenhub ticket for this work can be found [here](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1267).
Do not merge this PR until the tokens package has been merged including the changes from PR [#419](https://github.com/cds-snc/gcds-tokens/pull/419).
> style: update header spacing and border colour + width

- CHANGELOG.md
Update translations to changelog for versions v0.29.0 - v0.33.0.
> chore: update translations to changelog for versions v0.29.0 - v0.33.0

- packages/web/.storybook/preview-head.html
Add an additional check for the properties page we use for code display on the documentation through an iframe. When `externalLinks` is present in the query strings, the page will capture the `href` of the clicked link if it is external and will send that `href` to the top to allow the browser to navigate to the selected page.
To support https://github.com/cds-snc/gcds-docs/issues/515
1. Build and start storybook.
2. Create an html page with an iframe like below: 
```html
<iframe
title="Overview of gcds-footer properties and events."
src="http://localhost:6006/iframe.html?viewMode=docs&demo=true&singleStory=true&id=components-footer--events-properties&lang=en"
width="1200"
height="2150"
style="display: block; margin: 0 auto;"
frameBorder="0"
allow="clipboard-write"
></iframe>
```
3. Click …
> storybook: Add externalLinks check to prevent iframe navigation

- packages/web/src/components/gcds-nav-group/gcds-nav-group.tsx
- packages/web/src/components/gcds-nav-group/test/gcds-nav-group.spec.tsx
- packages/web/src/components/gcds-nav-link/gcds-nav-link.tsx
- packages/web/src/components/gcds-nav-link/test/gcds-nav-link.spec.tsx
As mentioned in https://github.com/cds-snc/gcds-components/issues/771, the top-nav mobile menu would close if a user expanded more than one sub-menu. To work in Safari, a `tabindex="0"` has been added to the `gcds-nav-link` and `gcds-nav-group` to properly focus each element and prevent the menu from closing.
Closes https://github.com/cds-snc/gcds-components/issues/771
```html
<gcds-top-nav label="topbar" alignment="right" lang="en">
<gcds-nav-group
menu-label="Contact us submenus"
open-trigger="Others"
>
<gcds-nav-link href="#form">Form</gcds-nav-link>
<gcds-nav-link href="#github">GitHub</gcds-nav-link>
<gcds-nav-link href="#slack">Slack</gcds-nav-link>
</gcds-nav-group>
<gcds-nav-link href="#home" slot="home">Home</gcds-nav-link>
<gcds-nav-link …
```
> fix: Mobile top-nav menu closing in Safari

- packages/web/src/components/gcds-date-input/stories/gcds-date-input.stories.tsx
- packages/web/src/components/gcds-fieldset/stories/gcds-fieldset.stories.tsx
- packages/web/src/components/gcds-input/stories/gcds-input.stories.tsx
- packages/web/src/components/gcds-radio-group/stories/gcds-radio-group.stories.tsx
- packages/web/src/components/gcds-select/stories/gcds-select.stories.tsx
Fix issues in storybook identified in https://github.com/cds-snc/design-gc-conception/issues/1504 and https://github.com/cds-snc/design-gc-conception/issues/1244.
- Updated the `compact` property for `gcds-date-input` to have the correct type of `string`
- Updated the `autocomplete` property for `gcds-input` to be an open text field instead of a select element
- Updated the events listed for `gcds-radio-group` to remove `gcdsRadioChange` event and list the `gcdsChange` event
- Updated the properties table for `gcds-select` and `gcds-fieldset` to show they both use slots
> storybook: Update/fix components events & properties table

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-footer/i18n/i18n.js
- packages/web/src/components/gcds-footer/test/gcds-footer.spec.tsx
Updating the spacing between the links and a small typo in the footer sub band to align with GC Web.
[Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1552) for this change.
> fix: update spacing between links and small typo in footer sub band

- packages/web/src/assets/css/global.css
This is a hotfix for the icon font face declaration to load through CDN links to avoid files not loading correctly.
> fix: icon font face declaration

- packages/web/src/components/gcds-card/gcds-card.tsx
- packages/web/src/components/gcds-card/test/gcds-card.spec.tsx
The shadow DOM HTML structure, when extracted and compiled, are not valid according to HTML5 spec content model. The concern is there are a paragraph inside a paragraph while a paragraph can only contain phrasing content and not flow content. 
Reference:
* List of HTML element that are valid as phrasing content - https://html.spec.whatwg.org/multipage/dom.html#phrasing-content
* the paragraph element, see the content model: https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element
1. Use a page with a gcds-card that contain a tag
2. Extract and manually compile the HTML structure of the shadow DOM imbrication
3. Ensure the extracted and compiled HTML are conform to HTML 5 content model specification.
I was able to observe the following HTML shadow dom structure for a …
> fix(gcds-card): Ensure shadow dom are structuraly valid according to spec

- packages/web/src/components/gcds-button/gcds-button.css
- packages/web/src/components/gcds-button/gcds-button.tsx
- packages/web/src/components/gcds-button/test/gcds-button.e2e.ts
Prevent `click` event from firing when button is disabled. Added additional logic to remove disabled attribute if `type="link` or `disabled="false"`.
For #819 
Using example below
```
<gcds-button button-role="start" onClick="buttonClicked()">Start</gcds-button>
<script>
function buttonClicked() {
console.log('clicked')
}
</script>
```
1. Copy the code example above into a document
2. Click the start button and observe 'clicked' in the console
3. Focus the element and click the button using the keyboard. Observe 'clicked' in the console.
4. Add the disabled attribute to the button and repeat the steps above. The button should no longer log anything to the console.
> fix: Prevent click event on disabled button

- .github/workflows/release-generator.yml
Update the release please workflow to use a new, dedicated GitHub app for releases.  The reason for the change is so that we can scale back use of the SRE read/write app.
- https://github.com/cds-snc/platform-core-services/issues/707
> chore:  switch to CDS Release Bot

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.css
- packages/web/src/components/gcds-pagination/gcds-pagination.css
- packages/web/src/components/gcds-select/gcds-select.css
- packages/web/src/components/gcds-topic-menu/gcds-topic-menu.css
This PR addresses inconsistent text scaling across desktop and mobile styles for multiple components. It was reported by a user in this [Freshdesk ticket.](https://gcdigital.slack.com/archives/C04U4PCDZ24/p1727183846723389)
The following components now have a font token for desktop & mobile:
- Topic menu
- Select
- File uploader
- Pagination
This is the [Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1196) for this change.
This PR can't be merged until it has the latest update to the tokens package.
> style: fix inconsistent text scaling across desktop + mobile styles for multiple components

- packages/web/src/components/gcds-details/gcds-details.css
- packages/web/src/index.html
Adjusting the spacing applied to slotted elements within the details component. Forcing a left and right margin of `0` to slotted elements was breaking the proper display of lists.
Here is a screenshot of what lists looked like within the details component before this change:
Here is a screenshot of what lists looked like within the details component now:
> style: fix details list spacing

- .github/workflows/run-tests.yml
For PRs that are not against main, the tests workflow file doesn't run. It works fine, but we're preparing to release the changes to the fieldset, checkboxes, and radios, and we should have a way to make sure the tests run on the branch or branches to make it easier to catch and work on. Adding a manual dispatch can allow us to selectively run it on a branch.
> chore: update runner for tests to have manual dispatch

- packages/web/src/components/gcds-link/gcds-link.tsx
- packages/web/src/components/gcds-link/test/gcds-link.spec.ts
- packages/web/src/components/gcds-search/gcds-search.tsx
- packages/web/src/components/gcds-search/test/gcds-search.spec.tsx
Align the structural markup of the GCDS `links` and `search` components with GCWeb patterns to ensure consistency when users (developers) use the two together on the same page.
- `gcds-link`: `role="link"` has been removed from the `<a>` tag.
- `gcds-search`: If the `suggested` property is not set or assigned, the list attribute on the input element is removed.
- `gcds-search`: Replace the `div` with a `section` for a more semantic markup.
This is the [Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1647) for the change.
> fix: align structural markup for link and search with GCWeb

- packages/web/README.md
The `dist/` folder on our `gcds-components` hasn't contained the `gcds/gcds.js` file since this commit [cds-snc/gcds-components@16732e5](https://github.com/cds-snc/gcds-components/commit/16732e5dc068cdb65d17f5485bb3189b2871836c). Removing the file from our layouts and installation instructions to avoid any confusion.
> chore: update installation instructions to remove outdated file

- package-lock.json
- packages/react-ssr/package.json
- packages/web/package.json
Updating prettier dependency to version `3.5.3`.
> chore: update prettier to 3.5.3

- packages/web/src/components/gcds-card/gcds-card.css
Removing redundant `z-index` from the card component link which is causing issues with header navigational elements as reported in [this issue](https://github.com/cds-snc/gcds-components/issues/875). While working on this, I also noticed that the card focus state wasn't displaying properly when using keyboard navigation, which has been fixed in this PR as well.
> fix: remove redundant z-index from card and fix focus state

- packages/web/src/components/gcds-nav-group/gcds-nav-group.css
- packages/web/src/components/gcds-nav-group/gcds-nav-group.tsx
- packages/web/src/components/gcds-top-nav/gcds-top-nav.css
- packages/web/src/index.html
The dropdown of the `nav-group` component gets partially cut-off in the `top-nav` component when the `top-nav` is set to `alignment=left` and doesn't use the `home` slot.
More details and screenshots can be found in [this issue](https://github.com/cds-snc/gcds-components/issues/857).
The dropdown alignment has been changed to be aligned left when the `top-nav` component uses `alignment=left`, and it will be aligned right, when the `top-nav` component uses `alignment=right`.
Using the code below:
```html
<gcds-header>
<gcds-top-nav slot="menu" label="Top navigation" alignment="left">
<gcds-nav-group
open-trigger="Nav group trigger"
menu-label="Nav group trigger"
>
<gcds-nav-link href="#" current>Nav link</gcds-nav-link>
<gcds-nav-link href="#">Nav link</gcds-nav-link>
<gcds-nav-link …
```
> fix: nav-group dropdown alignment within top-nav

- packages/web/src/components/gcds-button/gcds-button.tsx
Without `reflect: true`, the `disabled` prop was not reflected as an attribute on the `gcds-button` host element, causing styles like `:host([disabled])` to fail in Vue.
This led to missing disabled button styles in Vue, where props are passed but not automatically reflected as attributes.
Adding `reflect: true` ensures consistent styling across frameworks.
This is the [Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/gcds-components/862) for the task.
> fix: reflect gcds-button `disabled` prop to support :host([disabled]) styles

- packages/vue/tests/e2e/app.spec.ts
- packages/web/src/components/gcds-footer/gcds-footer.css
- packages/web/src/components/gcds-footer/i18n/i18n.js
- packages/web/src/components/gcds-footer/test/gcds-footer.spec.tsx
The footer was updated to match the [english links here](https://servicecanada.github.io/wet-boew-demos/gcweb-pr2545/templates/home/home-en.html) and the [french links here](https://servicecanada.github.io/wet-boew-demos/gcweb-pr2545/templates/home/home-fr.html).
Here is a preview of what the new footer looks like:
This is the [Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1680) for the details.
> feat: changes to footer links

- packages/react/package.json
Fix the configuration in the react package's `package.json` to point to the correct files.
Currently when using `@cdssnc/gcds-components-react@0.38.0`, you receive an error of `Cannot find module '@cdssnc/gcds-components-react' or its corresponding type declarations.` when importing any components.
1. In a react app, install the latest version of `@cdssnc/gcds-components-react`.
2. Import a gcds component.
3. Notice the `Cannot find module '@cdssnc/gcds-components-react` error on the import statement.
4. Using this branch, use `npm link` to link the local gcds-components-react package to your app.
5. Notice the import now resolves properly.
> fix: React output package.json configuration

- packages/web/src/components/gcds-date-input/gcds-date-input.tsx
- packages/web/src/components/gcds-input/gcds-input.tsx
- packages/web/src/components/gcds-select/gcds-select.tsx
- packages/web/src/components/gcds-textarea/gcds-textarea.tsx
While testing https://github.com/cds-snc/gcds-docs/pull/621, it was discovered that some GC Design System form components will not properly set the value for the HTML form when manually updating their `value` property. Add some extra logic to the `gcds-input`, `gcds-textarea`, `gcds-select` and `gcds-date-input` components to catch this behaviour.
Use the HTML form below:
```html
<form>
<gcds-input
input-id="form-name"
label="Name"
hint="Please enter your full name."
name="form-name"
></gcds-input>
<gcds-textarea
textarea-id="form-message"
label="Message"
hint="This is a hint."
character-count="400"
name="form-message"
></gcds-textarea>
<gcds-date-input
legend="Date input"
name="date-input"
format="full"
hint="Formatted: YYYY-MM-DD"
name="date-input"
></gcds-date-input>
<gcds-select …
```
> fix: Set form value on manual value update

- packages/web/stencil.config.ts
Set `addGlobalStyleToComponents` in the `stencil.config.ts` file to `false` to prevent stencil from adding the global styles CSS file into each component shadowRoot's [adoptedStyleSheet](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/adoptedStyleSheets) to prevent each component from loading more CSS then it needs to.
[More about this feature](https://stenciljs.com/docs/config-extras#addglobalstyletocomponents)
> build: Set addGlobalStyleToComponents to false

- packages/web/specs/components.json
- packages/web/src/components/gcds-textarea/gcds-textarea.tsx
- packages/web/src/components/gcds-textarea/test/gcds-textarea.spec.ts
Fixes #916 
Build and consume the components and angular package from this PR
Test with this code reproduction URL:
https://github.com/LagaceM/gcds-textarea-bug
I did further testing on this by adding a clear and a reset like so:
```
public clearTextarea() {
this.formControl.setValue('');
}
public resetTextarea() {
this.formControl.setValue(this.defaultTextareaValue);
}
```
and no errors so far.
> fix(text-area): add null check in watchValue for shadowElement

- packages/web/src/components/gcds-select/gcds-select.tsx
- packages/web/src/components/gcds-select/test/gcds-select.spec.tsx
A user reported an issue with the `select` component where ampersands (&) in options were being rendered incorrectly.
The issue stems from how the component is rendering the `option` content. The component is using `innerHTML` to set the option content, which includes encoded HTML entities (e.g., `&`). When rendered via JSX, these entities are being escaped again, causing them to appear incorrectly (e.g., `&amp;` instead of `&`).
Refactored the rendering logic for the `select` slot to use `textContent` unstead of `innerHTML` to prevent double-escaping of entities like `&`.
The reported user issue can be found [here](https://cds-snc.freshdesk.com/a/tickets/24269).
1. Using the `main` branch, add the following code to your test page:
```
<gcds-select
select-id="select-props"
label="Label" …
```
> fix(select): prevent double-escaping of special characters in select options

- packages/web/src/components/gcds-checkboxes/checkbox.tsx
- packages/web/src/components/gcds-checkboxes/gcds-checkboxes.tsx
- packages/web/src/components/gcds-checkboxes/test/gcds-checkboxes.spec.tsx
Fix for https://github.com/cds-snc/design-gc-conception/issues/1892
Issue: GcdsChange on GcdsCheckboxes doesn't populate the values on the `detail` object when it is emitted
When using gcds-checkboxes, listen to the gcdsChange event being emitted and check for the value in the detail object.
On the fable app built in react, I tested it in the SubmitHoliday.tsx file like this:
```javascript
document.addEventListener('gcdsInput', (e: any) => {
if (e.target && (e.target.tagName === 'GCDS-CHECKBOXES' || e.target.tagName === 'GCDS-RADIOS')) {
console.log('gcdsInput:', {
component: e.target.tagName,
name: e.target.name,
detail: e.detail,
detailType: typeof e.detail,
isArray: Array.isArray(e.detail)
});
}
document.addEventListener('gcdsChange', (e: any) => {
if (e.target && (e.target.tagName === …
```
> fix(gcds-checkboxes): handle onChange events and emit values

- packages/web/src/components/gcds-topic-menu/gcds-topic-menu.css
Currently when hovering over text in the theme and topic menu component, the background colour changes faster than the text colour, leading to low-contrast text. I adjusted the styling to change the background colour at the same time as the text.
This style change is a bug fix for [this ticket](https://github.com/cds-snc/gcds-components/issues/847).
This is the [Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/gcds-components/847) for the change.
How to test
1. Using the main branch, add the following code to your test page:
```
<gcds-topic-menu ></gcds-topic-menu>
```
2. Click on the menu button and hover over any of the menu items on the left hand side. Notice that the link text colour on hover switches from white to black …
> style: fix topic menu link background on hover
