- package-lock.json
- package.json
- src/components.d.ts
- src/components/gcds-error-message/gcds-error-message.css
- src/components/gcds-error-message/gcds-error-message.spec.ts
- src/components/gcds-error-message/gcds-error-message.tsx
- src/components/gcds-error-message/readme.md
- src/components/gcds-hint/gcds-hint.css
- src/components/gcds-hint/gcds-hint.spec.ts
- src/components/gcds-hint/gcds-hint.tsx
- src/components/gcds-hint/readme.md
- src/components/gcds-input/gcds-input.css
- src/components/gcds-input/gcds-input.e2e.ts
- src/components/gcds-input/gcds-input.spec.ts
- src/components/gcds-input/gcds-input.tsx
- src/components/gcds-input/readme.md
- src/components/gcds-label/gcds-label.css
- src/components/gcds-label/gcds-label.spec.ts
- src/components/gcds-label/gcds-label.tsx
- src/components/gcds-label/readme.md
- src/styles/global.css
- src/styles/variables/_variables.scss
- src/styles/variables/variables.css
Adding new input component, including error message, hint, and label.
Ticket: https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/cds-snc/design-gc-conception/159
> Feat 152 text input component

- src/components.d.ts
- src/components/gcds-error-message/gcds-error-message.css
- src/components/gcds-error-message/gcds-error-message.spec.ts
- src/components/gcds-error-message/gcds-error-message.tsx
- src/components/gcds-hint/gcds-hint.css
- src/components/gcds-input/gcds-input.css
- src/components/gcds-input/gcds-input.spec.ts
- src/components/gcds-input/gcds-input.tsx
- src/components/gcds-input/readme.md
- src/components/gcds-label/gcds-label.css
- src/components/gcds-textarea/gcds-textarea.css
- src/components/gcds-textarea/gcds-textarea.spec.ts
- src/components/gcds-textarea/gcds-textarea.tsx
- src/components/gcds-textarea/readme.md
Updated design for input and textarea components.
Note: The hardcoded colour and spacing values will need to be updated once the design tokens are done.
> update design for input and textarea components

- package-lock.json
- package.json
- src/components/gcds-site-menu/gcds-site-menu.css
- src/components/gcds-site-menu/gcds-site-menu.tsx
- src/styles/global.css
CSS rewrite for the site-menu component.
> Rewrite site-menu css

- src/components.d.ts
- src/components/gcds-button/gcds-button.css
- src/components/gcds-input/gcds-input.css
- src/components/gcds-input/gcds-input.tsx
- src/components/gcds-label/gcds-label.css
- src/components/gcds-textarea/gcds-textarea.css
- src/components/gcds-textarea/gcds-textarea.spec.ts
- src/components/gcds-textarea/gcds-textarea.tsx
- removed red colour from the required label
- fixed input size + textarea col props to be responsive
- fix button active style
> Input component updates

- package-lock.json
- package.json
- src/components/gcds-input/readme.md
- src/components/gcds-textarea/readme.md
- stencil.config.ts
Update stencil config to include gcds.js file.
> update stencil config + input and textarea readme

- src/components/gcds-footer/gcds-footer.css
- src/components/gcds-header/gcds-header.css
- src/components/gcds-lang-toggle/gcds-lang-toggle.css
- src/components/gcds-signature/gcds-signature.css
- src/styles/global.css
- add header tokens
- add signature tokens
- add footer tokens
> Add header and footer tokens

- package.json
- src/components.d.ts
- src/components/gcds-error-message/readme.md
- src/components/gcds-hint/readme.md
- src/components/gcds-label/readme.md
- src/components/gcds-select/gcds-select.css
- src/components/gcds-select/gcds-select.tsx
- src/components/gcds-select/readme.md
- src/components/gcds-select/test/gcds-select.e2e.ts
- src/components/gcds-select/test/gcds-select.spec.tsx
- src/components/gcds-verify-banner/readme.md
- src/styles/global.css
> add gcds-select component

- package.json
- src/components.d.ts
- src/components/gcds-icon/gcds-icon.css
- src/components/gcds-icon/gcds-icon.tsx
- src/components/gcds-icon/readme.md
- src/components/gcds-icon/test/gcds-icon.e2e.ts
- src/components/gcds-icon/test/gcds-icon.spec.ts
Add icon component using Font Awesome.
> add icon component

- package.json
- src/components.d.ts
- src/components/gcds-error-message/readme.md
- src/components/gcds-file-uploader/gcds-file-uploader.css
- src/components/gcds-file-uploader/gcds-file-uploader.tsx
- src/components/gcds-file-uploader/readme.md
- src/components/gcds-file-uploader/test/gcds-file-uploader.e2e.ts
- src/components/gcds-file-uploader/test/gcds-file-uploader.spec.tsx
- src/components/gcds-hint/readme.md
- src/components/gcds-icon/readme.md
- src/components/gcds-label/readme.md
- src/styles/global.css
Add gcds-file-uploader component.
The file uploader allows users to upload one or multiple files to a specific location.
> add gcds-file-uploader component

- package.json
- src/components.d.ts
- src/components/gcds-stepper/gcds-stepper.css
- src/components/gcds-stepper/gcds-stepper.tsx
- src/components/gcds-stepper/readme.md
- src/components/gcds-stepper/test/gcds-stepper.e2e.ts
- src/components/gcds-stepper/test/gcds-stepper.spec.tsx
- src/styles/global.css
Adding gcds-stepper component - A stepper guides users through multi-step flows with numbered steps.
Properties:
- **current-step**: The step the user is currently on
- **total-steps**: The total number of steps
- **lang**: Language of the component
> add gcds-stepper component

- package.json
- src/components.d.ts
- src/components/gcds-details/gcds-details.css
- src/components/gcds-details/gcds-details.tsx
- src/components/gcds-details/readme.md
- src/components/gcds-details/test/gcds-details.e2e.ts
- src/components/gcds-details/test/gcds-details.spec.tsx
Adding the gcds-details component.
The details component (also called accordion) is an interactive title/summary that shows or hides related, additional content when selected. It is typically used in a list and provides the user with a high-level overview of content that is not crucial to read in full. It reduces the need to scroll.
Properties
details-title: The title for the details component summarizes the panel content.
open: Defines if the details panel is open by default or not.
Slotted Elements
Slot
The details slot is content that is associated with the details title. It can include text only or additional elements such as buttons that allow the user to take action.
> add gcds-details component

- packages/angular/src/lib/stencil-generated/components.ts
- packages/angular/src/lib/stencil-generated/index.ts
- packages/react/src/components/stencil-generated/index.ts
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-date-modified/gcds-date-modified.css
- packages/web/src/components/gcds-date-modified/gcds-date-modified.tsx
- packages/web/src/components/gcds-date-modified/readme.md
- packages/web/src/components/gcds-date-modified/test/gcds-date-modified.spec.tsx
- packages/web/src/index.html
Add `gcds-date-modified` component.
```
<gcds-date-modified>
2022-03-03
</gcds-date-modified>
```
> Date modified component

- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs.css
- packages/web/src/components/gcds-header/gcds-header.css
- packages/web/src/components/gcds-site-menu/gcds-site-menu.css
- styles/global.css
Update component tokens to fix display issues.
- `gcds-site-menu`: Change container token to current token
- `gcds-header`: Add `!important` to avoid overwriting margin styles
- `gcds-breadcrumbs`:Add `!important` to avoid overwriting margin styles on slotted first-child list item
- `gcds-footer`: Token update to fix wordmark margin
> Varous component and token fixes

- packages/angular/src/lib/stencil-generated/components.ts
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-alert/gcds-alert.css
- packages/web/src/components/gcds-alert/gcds-alert.tsx
- packages/web/src/components/gcds-alert/readme.md
- packages/web/src/components/gcds-alert/test/gcds-alert.spec.tsx
- styles/global.css
Update alert design + add new tokens.
- Added a new prop to hide the role icon.
- Renamed "max-content-width" prop to "container" for better consistency with other components.
> update alert design + tokens

- packages/angular/src/lib/stencil-generated/components.ts
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-footer/gcds-footer.tsx
- packages/web/src/components/gcds-footer/readme.md
- packages/web/src/components/gcds-footer/test/gcds-footer.spec.tsx
Add new prop `sub-links` to `gcds-footer` and removed `list` slot.
> Add new footer prop: sub-links

- README.md
- packages/angular/README.md
- packages/angular/package.json
- packages/react/README.md
- packages/react/package.json
- packages/web/README.md
- packages/web/package.json
- packages/web/stencil.config.ts
Update readmes for all packages with new version (English only for now0. 
Update packages to use new site url and new npm org.
> Update readme and package.jsons

- packages/web/src/components/gcds-button/gcds-button.css
- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.css
- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.tsx
- styles/global.css
- update button styles
- update file uploader styles
> Token updates

- .github/workflows/compile-and-publish.yml
- .github/workflows/run-tests.yml
Update github actions to install only web package to run tests.
> Update actions to install correct packages

- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.css
- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.tsx
- styles/global.css
Add border to gcds-file-uploader remove button.
> add border to gcds-file-uploader remove button

- README.md
- packages/angular/README.md
- packages/react/README.md
- packages/web/README.md
Add French translations for all package READMEs.
> Add French side of READMEs for all packages

- packages/web/src/components/gcds-pagination/gcds-pagination.css
Fix typo in pagination token `--gcds-pagination-default-text`
> Fix typo in pagination token

- README.md
- packages/angular/README.md
- packages/angular/package.json
- packages/react/README.md
- packages/react/package.json
- packages/web/README.md
- packages/web/package.json
Update readme and package.json files to new url for doc site
> Update url in readme and package.json files

- packages/web/package.json
- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs-item.css
- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs.css
- packages/web/src/components/gcds-details/gcds-details.css
- This update is using tokens created from this tokens PR
- Updating the breadcrumb component to match the states outlined in our [figma design file](https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/Canadian-Digital-Service%E2%80%A8---GC-Design-System?node-id=2353-7841&t=Xltq5UH5rAP3FmxQ-0)
| Before | After |
|--------|-------|
|  ![Breadcrumb-before](https://user-images.githubusercontent.com/30609058/228629666-317dfb9c-5ac3-440d-8f54-a469a2f99285.gif) | ![Breadcrumb-after](https://user-images.githubusercontent.com/30609058/228629721-0d6ca913-efc3-48b4-a346-8c1cb2f3b251.gif) |
- Updating the details component to match the states outlined in our [figma design file](https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/Canadian-Digital-Service%E2%80%A8---GC-Design-System?node-id=1097-2733&t=Xlt …
> Breadcrumb details update

- packages/web/src/components/gcds-button/gcds-button.css
- packages/web/src/components/gcds-lang-toggle/gcds-lang-toggle.css
- States have been updated to match the states in [our figma file (lang-toggle)](https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/Canadian-Digital-Service%E2%80%A8---GC-Design-System?node-id=1780-5094&t=AwIiCGSLOD0jPlPn-0)
| Before | After |
|--------|-------|
|  ![lang-toggle-after](https://user-images.githubusercontent.com/30609058/233517471-2daa6db3-bf7f-4ec2-bdd8-46377709de40.gif) | ![lang-toggle-before](https://user-images.githubusercontent.com/30609058/233517506-13f134c0-a2b2-4f64-9df6-ff3f5baa0b75.gif) |
- States have been updated to match the states in [our figma file (button)](https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/Canadian-Digital-Service%E2%80%A8---GC-Design-System?node-id=2319-7955&t=AwIiCGSLOD0jPlPn-0)
| Before |
|-------|
| …
> Lang toggle and button state update

- packages/angular/src/lib/stencil-generated/angular-component-lib/utils.ts
- packages/angular/src/lib/stencil-generated/components.ts
- packages/web/src/components/gcds-error-summary/gcds-error-summary.tsx
- packages/web/src/components/gcds-fieldset/gcds-fieldset.css
- packages/web/src/components/gcds-fieldset/gcds-fieldset.tsx
- packages/web/src/components/gcds-fieldset/test/gcds-fieldset.spec.tsx
- packages/web/src/index.html
- packages/web/src/validators/fieldset-validators/fieldset-validators.ts
Change `gcds-fieldset` to remove shadowDom to function better with other form elements.
> Change gcds-fieldset to remove shadowDom

- packages/react/src/components/stencil-generated/react-component-lib/createComponent.tsx
- packages/react/src/components/stencil-generated/react-component-lib/createOverlayComponent.tsx
- packages/react/src/components/stencil-generated/react-component-lib/utils/case.ts
- packages/react/src/components/stencil-generated/react-component-lib/utils/index.tsx
- packages/web/src/components/gcds-error-summary/gcds-error-summary.tsx
Add `hasSubmitted` state to error summary to fix triggering before `submit` event.
Also some React build files.
> Fix error summary triggering before submit

- packages/web/src/index.html
- add gcds-container component to demo
- update UF border class
> add gcds-container component to demo + update UF border class

- .github/workflows/publish-storybook-staging.yml
- .github/workflows/run-tests.yml
Modify current GitHub actions to allow publishing of a staging storybook.
> GitHub action changes for staging env

- CHANGELOG.md
Add changelog file to project. The current changelog features from `v0.10.0` and up.
> Add CHANGELOG.md to project

- CHANGELOG.md
- packages/web/package-lock.json
- packages/web/package.json
- Update changelog to feature latest updates for `v0.11.0`.
- Update `@cdssnc/gcds-tokens` package
> Update changelog + update token package

- packages/angular/src/lib/stencil-generated/components.ts
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-nav-group/gcds-nav-group.css
- packages/web/src/components/gcds-nav-group/gcds-nav-group.tsx
- packages/web/src/components/gcds-nav-group/i18n/i18n.js
- packages/web/src/components/gcds-nav-group/readme.md
- packages/web/src/components/gcds-nav-group/test/gcds-nav-group.e2e.ts
- packages/web/src/components/gcds-nav-group/test/gcds-nav-group.spec.tsx
- packages/web/src/components/gcds-nav-link/gcds-nav-link.css
- packages/web/src/components/gcds-side-nav/gcds-side-nav.tsx
- packages/web/src/components/gcds-side-nav/test/gcds-side-nav.spec.tsx
- packages/web/src/components/gcds-top-nav/gcds-top-nav.tsx
- packages/web/src/components/gcds-top-nav/test/gcds-top-nav.spec.tsx
- packages/web/src/index.html
- add tablet styling for top- and side-nav
> add tablet styling for top- and side-nav

- CHANGELOG.md
- lerna.json
- packages/angular/package.json
- packages/react/package-lock.json
- packages/react/package.json
- packages/web/package-lock.json
- packages/web/package.json
Update changelog with new changes and version for release
> Update version + changelog

- CHANGELOG.md
- lerna.json
- packages/angular/package-lock.json
- packages/angular/package.json
- packages/react/package-lock.json
- packages/react/package.json
- packages/web/package-lock.json
- packages/web/package.json
Update changelog and package versions for release.
> Update for v0.12.1 release

- package.json
- packages/web/package.json
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-nav-group/gcds-nav-group.css
- packages/web/src/components/gcds-nav-link/gcds-nav-link.css
- Assuring that styles match the figma file: https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/Canadian-Digital-Service%E2%80%A8---GC-Design-System?type=design&node-id=4738-10793&mode=design&t=0EOrdnCkCAEGGaNo-0
| Before | ![topnav-before](https://github.com/cds-snc/gcds-components/assets/30609058/15cdf933-152a-4e72-91a1-4e06a32ed1b5)|
|--------|---|
| After  |  ![topnav-after](https://github.com/cds-snc/gcds-components/assets/30609058/76a05815-835b-4073-bbe8-4a1072aa29c0) |
> Topnav fixes

- packages/web/.storybook/preview-head.html
- packages/web/src/components/gcds-container/stories/gcds-container.stories.tsx
- packages/web/src/components/gcds-container/stories/overview.mdx
- packages/web/src/components/gcds-icon/stories/gcds-icon.stories.tsx
- packages/web/src/components/gcds-icon/stories/overview.mdx
- packages/web/src/components/gcds-icon/stories/properties.mdx
- Add stories for icon component
- Add resources links to container story
- Add margin + padding stories for container
> Storybook updates

- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-file-uploader/i18n/i18n.js
- packages/web/src/components/gcds-file-uploader/test/gcds-file-uploader.spec.tsx
- packages/web/src/components/gcds-header/gcds-header.css
- packages/web/src/components/gcds-header/gcds-header.tsx
- packages/web/src/components/gcds-header/test/gcds-header.spec.tsx
- packages/web/src/components/gcds-signature/gcds-signature.css
- Update file uploader button text to "choose file".
- Add footer + header margins for signature in footer + header css, remove from signature css to avoid incorrect margins in other places
- Rename header topnav slot to skip-to-nav to avoid confusion with new top-nav component.
[Depending on #146](https://github.com/cds-snc/gcds-tokens/pull/146)
> Smaller updates

- packages/web/.storybook/preview-head.html
- packages/web/src/components/gcds-breadcrumbs/stories/gcds-breadcrumbs.stories.tsx
- packages/web/src/components/gcds-card/stories/gcds-card.stories.tsx
- packages/web/src/components/gcds-checkbox/stories/gcds-checkbox.stories.tsx
- packages/web/src/components/gcds-error-message/stories/gcds-error-message.stories.tsx
- packages/web/src/components/gcds-error-summary/stories/gcds-error-summary.stories.tsx
- packages/web/src/components/gcds-error-summary/stories/overview.mdx
- packages/web/src/components/gcds-error-summary/stories/properties.mdx
- packages/web/src/components/gcds-fieldset/stories/gcds-fieldset.stories.tsx
- packages/web/src/components/gcds-file-uploader/stories/gcds-file-uploader.stories.tsx
- packages/web/src/components/gcds-file-uploader/stories/overview.mdx
- packages/web/src/components/gcds-file-uploader/stories/properties.mdx
- packages/web/src/components/gcds-footer/stories/gcds-footer.stories.tsx
- packages/web/src/components/gcds-input/stories/gcds-input.stories.tsx
- packages/web/src/components/gcds-lang-toggle/stories/gcds-lang-toggle.stories.tsx
- packages/web/src/components/gcds-lang-toggle/stories/overview.mdx
- packages/web/src/components/gcds-lang-toggle/stories/properties.mdx
- packages/web/src/components/gcds-nav-group/stories/gcds-nav-group.stories.tsx
- packages/web/src/components/gcds-nav-link/stories/gcds-nav-link.stories.tsx
- packages/web/src/components/gcds-pagination/stories/gcds-pagination.stories.tsx
- packages/web/src/components/gcds-radio/stories/gcds-radio.stories.tsx
- packages/web/src/components/gcds-select/stories/gcds-select.stories.tsx
- packages/web/src/components/gcds-side-nav/stories/gcds-side-nav.stories.tsx
- packages/web/src/components/gcds-stepper/stories/gcds-stepper.stories.tsx
- packages/web/src/components/gcds-textarea/stories/gcds-textarea.stories.tsx
- packages/web/src/components/gcds-top-nav/stories/gcds-top-nav.stories.tsx
- Align storybook story content with anatomy content in Figma & on docs site
- Add missing error summary stories
- Add missing lang-toggle stories
- Add missing file uploader stories
- Update input + select error stories
> Update stories content

- CHANGELOG.md
- lerna.json
- packages/angular/package-lock.json
- packages/angular/package.json
- packages/react/package-lock.json
- packages/react/package.json
- packages/web/package-lock.json
- packages/web/package.json
Prep for `v0.13.0` release. Update changelog and package versions.
> Prep v0.13.0

- .github/workflows/compile-and-publish.yml
- .github/workflows/renovate-pr-build.yml
Add GitHub action to test changes made by pull requests by Renovate. Pull requests will run extra actions when the pull request is labelled with `Renovate`.
> Add action for testing Renovate changes

- packages/web/src/components/gcds-textarea/stories/gcds-textarea.stories.tsx
- packages/web/src/components/gcds-textarea/stories/overview.mdx
- packages/web/src/components/gcds-textarea/stories/properties.mdx
Add missing stories for textarea component.
> add missing textarea stories

- CHANGELOG.md
- lerna.json
- packages/angular/package-lock.json
- packages/angular/package.json
- packages/react/package-lock.json
- packages/react/package.json
- packages/web/package-lock.json
- packages/web/package.json
Update package files and changelog for `v0.14.0` release
> Prep for v0.14.0 update

- packages/web/package-lock.json
- packages/web/package.json
Remove lone `stencil@0.0.5` file from web package since it has a security risk
> Remove lone stencil package

- packages/web/src/components/gcds-button/stories/gcds-button.stories.js
- packages/web/src/components/gcds-button/stories/overview.mdx
Very small PR... Adding a story to show an example of a button with an icon inside it.
> add story for button with icon

- packages/web/src/components/gcds-nav-group/stories/gcds-nav-group.stories.tsx
- packages/web/src/components/gcds-nav-group/stories/overview.mdx
- packages/web/src/components/gcds-nav-group/stories/properties.mdx
- packages/web/src/components/gcds-nav-link/stories/gcds-nav-link.stories.tsx
- packages/web/src/components/gcds-nav-link/stories/overview.mdx
- packages/web/src/components/gcds-nav-link/stories/properties.mdx
- packages/web/src/components/gcds-side-nav/stories/gcds-side-nav.stories.tsx
- packages/web/src/components/gcds-side-nav/stories/overview.mdx
- packages/web/src/components/gcds-side-nav/stories/properties.mdx
- packages/web/src/components/gcds-top-nav/stories/gcds-top-nav.stories.tsx
- packages/web/src/components/gcds-top-nav/stories/overview.mdx
- packages/web/src/components/gcds-top-nav/stories/properties.mdx
Add the overview and playground pages to the navigation components in storybook.
> Add overview + playground pages for navigation components

- packages/web/.storybook/preview-head.html
Improve Storybook `Hide code` & `Copy` button styling for better accessibility.
Button styling before:
Button styling after:
> improve storybook buttons styling for better accessibility 

- packages/web/src/components/gcds-signature/gcds-signature.tsx
- packages/web/src/components/gcds-signature/readme.md
- packages/web/src/components/gcds-signature/stories/gcds-signature.stories.tsx
- packages/web/src/components/gcds-signature/test/gcds-signature.spec.tsx
- packages/web/src/components/gcds-topic-menu/gcds-topic-menu.css
- Signature: add default value for type and variant.
- Fix topic menu focus border for menu btn
@ethanWallace the `has-link` prop for the signature component currently doesn't have a default value, but the Storybook story shows the default value as `false`. Should we set the default value to `false` in the component as well?
> Small adjustments

- CHANGELOG.md
Add French translations for changelog.
> add french translations for changelog

- CHANGELOG.md
- lerna.json
- packages/angular/package-lock.json
- packages/angular/package.json
- packages/react/package-lock.json
- packages/react/package.json
- packages/web/package-lock.json
- packages/web/package.json
Update changelog and package versions for `v0.15.0` release
> Prep for v0.15.0

- CHANGELOG.md
- lerna.json
- packages/angular/package-lock.json
- packages/angular/package.json
- packages/react/package-lock.json
- packages/react/package.json
- packages/web/package-lock.json
- packages/web/package.json
Update changelog and package versions for v 0.16.0 release
> Prep for v 0.16.0

- CHANGELOG.md
- lerna.json
- packages/angular/package-lock.json
- packages/angular/package.json
- packages/react/package-lock.json
- packages/react/package.json
- packages/web/package-lock.json
- packages/web/package.json
Update version + changelog for v 0.17.0.
> Update version + changelog for v 0.17.0

- CHANGELOG.md
> translated v.0.14 to .17 in changelog
---
> traduction des version 0.14 à 0.17 dans le changelog
> translated v0.14 to 17 in CHANGELOG.md

- packages/web/src/components/gcds-link/i18n/i18n.js
- packages/web/src/components/gcds-link/stories/gcds-link.stories.js
- packages/web/src/index.html
- Update demo content
- Update link boolean + radio toggles to use select for better a11y
- Slightly updated the aria-label text for links to be displayed + read a little bit nicer by screen readers
> update demo content

- packages/angular/src/lib/stencil-generated/components.ts
- packages/angular/src/lib/stencil-generated/index.ts
- packages/react/src/components/stencil-generated/index.ts
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/components.d.ts
- packages/web/src/components/gcds-grid/gcds-grid-col.css
- packages/web/src/components/gcds-grid/gcds-grid-col.tsx
- packages/web/src/components/gcds-grid/gcds-grid.css
- packages/web/src/components/gcds-grid/gcds-grid.tsx
- packages/web/src/components/gcds-grid/readme.md
- packages/web/src/components/gcds-grid/stories/gcds-grid.stories.tsx
- packages/web/src/components/gcds-grid/stories/overview.mdx
- packages/web/src/components/gcds-grid/test/gcds-grid.spec.ts
- packages/web/src/index.html
Adding the ability to add individually sized grid columns to grids as well as allowing to set equal height rows.
> feat: add new grid functionality

- packages/web/src/components/gcds-header/stories/gcds-header.stories.tsx
Fixing the header slots for breadcrumbs and search for the React code preview.
> fix header slots in story

- packages/web/src/components/gcds-fieldset/gcds-fieldset.css
CSS rewrite for the fieldset component to add new CSS features like layers, etc.
> refactor: css rewrite fieldset

- packages/web/src/components/gcds-nav-link/gcds-nav-link.css
CSS rewrite for the nav-link component to add new CSS features like layers, etc.
> refactor: css rewrite nav-link

- packages/web/src/components/gcds-stepper/gcds-stepper.css
CSS rewrite for the stepper component to add new CSS features like layers, etc.
> refactor: css rewrite stepper

- packages/web/src/components/gcds-sr-only/gcds-sr-only.css
CSS rewrite for the sr-only component to add new CSS features like layers, etc.
> refactor: css rewrite sr-only

- packages/web/src/components/gcds-phase-banner/gcds-phase-banner.css
CSS rewrite for the phase banner component to add new CSS features like layers, etc.
> refactor: css rewrite phase banner

- packages/web/src/components/gcds-label/gcds-label.css
CSS rewrite for the label component to add new CSS features like layers, etc.
> refactor: css rewrite label

- packages/web/src/components/gcds-select/gcds-select.css
CSS rewrite for the select component to add new CSS features like layers, etc.
> refactor: css rewrite select

- packages/web/src/components/gcds-radio/gcds-radio.css
CSS rewrite for the radio component to add new CSS features like layers, etc.
> refactor: css rewrite radio

- packages/web/src/components/gcds-header/gcds-header.css
CSS rewrite for the header component to add new CSS features like layers, etc.
> refactor: css rewrite header

- packages/web/src/components/gcds-card/gcds-card.css
CSS rewrite for the card component to add new CSS features like layers, etc.
> refactor: css rewrite card

- packages/web/src/components/gcds-signature/gcds-signature.css
- packages/web/src/components/gcds-signature/gcds-signature.tsx
- packages/web/src/components/gcds-signature/test/gcds-signature.spec.tsx
CSS rewrite for the signature component to add new CSS features like layers, etc.
> refactor: css rewrite signature

- packages/web/src/components/gcds-date-modified/gcds-date-modified.css
- packages/web/src/components/gcds-date-modified/gcds-date-modified.tsx
- packages/web/src/components/gcds-date-modified/test/gcds-date-modified.spec.tsx
CSS rewrite for the date-modified component to add new CSS features like layers, etc.
> refactor: CSS rewrite date-modified

- packages/web/src/components/gcds-text/gcds-text.css
CSS rewrite for the text component to add new CSS features like layers, etc.
> refactor: css rewrite text

- packages/web/src/components/gcds-heading/gcds-heading.css
CSS rewrite for the heading component to add new CSS features like layers, etc.
> refactor: css rewrite heading

- packages/web/src/components/gcds-alert/gcds-alert.css
- packages/web/src/components/gcds-alert/gcds-alert.tsx
- packages/web/src/components/gcds-alert/test/gcds-alert.spec.tsx
CSS rewrite for the alert component to add new CSS features like layers, etc.
> refactor: css rewrite alert

- packages/web/src/components/gcds-verify-banner/gcds-verify-banner.css
CSS rewrite for the verify-banner component to add new CSS features like layers, etc.
> refactor: css rewrite verify-banner

- packages/web/src/components/gcds-link/gcds-link.css
- packages/web/src/components/gcds-link/gcds-link.tsx
- packages/web/src/components/gcds-link/test/gcds-link.spec.ts
CSS rewrite for the link component to add new CSS features like layers, etc.
> refactor: css rewrite link

- packages/web/src/components/gcds-footer/gcds-footer.css
CSS rewrite for the footer component to add new CSS features like layers, etc.
> refactor: css rewrite footer

- packages/web/src/components/gcds-top-nav/gcds-top-nav.css
- packages/web/src/components/gcds-top-nav/gcds-top-nav.tsx
- packages/web/src/components/gcds-top-nav/test/gcds-top-nav.spec.tsx
CSS rewrite for the top-nav component to add new CSS features like layers, etc.
Note: Had to add a wrapper div to be able to use container queries.
> refactor: css rewrite top-nav

- packages/web/src/components/gcds-grid/gcds-grid-col.css
- packages/web/src/components/gcds-grid/gcds-grid.css
CSS rewrite for the grid component to add new CSS features like layers, etc.
> refactor: css rewrite grid

- packages/web/src/components/gcds-topic-menu/gcds-topic-menu.css
CSS rewrite for the topic-menu component to add new CSS features like layers, etc.
> refactor: css rewrite topic menu

- packages/web/src/components/gcds-nav-group/gcds-nav-group.css
CSS rewrite for the nav-group component to add new CSS features like layers, etc.
> refactor: css rewrite nav group

- packages/web/src/components/gcds-file-uploader/gcds-file-uploader.css
CSS rewrite for the file-uploader component to add new CSS features like layers, etc.
> refactor: css rewrite file-uploader

- packages/web/src/components/gcds-pagination/gcds-pagination.css
- packages/web/src/components/gcds-pagination/gcds-pagination.tsx
- packages/web/src/components/gcds-pagination/test/gcds-pagination.e2e.ts
- packages/web/src/components/gcds-pagination/test/gcds-pagination.spec.tsx
- packages/web/src/components/gcds-pagination/utils/render.tsx
CSS rewrite for the pagination component to add new CSS features like layers, etc.
> refactor: css rewrite pagination

- CHANGELOG.md
Add french translation for version `0.17.1` updates.
> chore: add changelog translation

- packages/web/src/components/gcds-side-nav/gcds-side-nav.css
- packages/web/src/components/gcds-side-nav/gcds-side-nav.tsx
- packages/web/src/components/gcds-side-nav/test/gcds-side-nav.spec.tsx
- packages/web/src/index.html
CSS rewrite for the side-nav component to add new CSS features like layers, etc.
> refactor: css rewrite side-nav

- .github/workflows/build-components.yml
Adding `workflow_dispatch:` so we can run this action manually, and also run this on the ssr branch automatically as well.
> Add workflow dispatch to build-components.yml

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-link/gcds-link.css
Update the tokens package to the latest version + add mobile font size to the link component.
> chore: update tokens + add mobile font size to link

- packages/web/src/components/gcds-card/stories/gcds-card.stories.tsx
- packages/web/src/components/gcds-card/stories/properties.mdx
- packages/web/src/components/gcds-checkbox/stories/gcds-checkbox.stories.tsx
- packages/web/src/components/gcds-checkbox/stories/properties.mdx
- packages/web/src/components/gcds-error-message/stories/gcds-error-message.stories.tsx
- packages/web/src/components/gcds-fieldset/stories/gcds-fieldset.stories.tsx
- packages/web/src/components/gcds-fieldset/stories/properties.mdx
- packages/web/src/components/gcds-file-uploader/stories/gcds-file-uploader.stories.tsx
- packages/web/src/components/gcds-footer/stories/gcds-footer.stories.tsx
- packages/web/src/components/gcds-footer/stories/properties.mdx
- packages/web/src/components/gcds-header/stories/gcds-header.stories.tsx
- packages/web/src/components/gcds-header/stories/properties.mdx
- packages/web/src/components/gcds-icon/stories/gcds-icon.stories.tsx
- packages/web/src/components/gcds-input/stories/gcds-input.stories.tsx
- packages/web/src/components/gcds-link/stories/gcds-link.stories.js
- packages/web/src/components/gcds-nav-group/stories/gcds-nav-group.stories.tsx
- packages/web/src/components/gcds-nav-link/stories/gcds-nav-link.stories.tsx
- packages/web/src/components/gcds-pagination/stories/gcds-pagination.stories.tsx
- packages/web/src/components/gcds-pagination/stories/properties.mdx
- packages/web/src/components/gcds-radio/stories/gcds-radio.stories.tsx
- packages/web/src/components/gcds-radio/stories/properties.mdx
- packages/web/src/components/gcds-select/stories/gcds-select.stories.tsx
- packages/web/src/components/gcds-side-nav/stories/gcds-side-nav.stories.tsx
- packages/web/src/components/gcds-textarea/stories/gcds-textarea.stories.tsx
- packages/web/src/components/gcds-top-nav/stories/gcds-top-nav.stories.tsx
- packages/web/src/utils/storybook/component-properties.js
- Ensure all the id's for stories within a component are unique to provide better support for screen readers
- Add a `props` story for each component to protect the `default` story from being altered
- Change `lang` control from `radio` to `select` for better screen reader support
> chore(storybook): ensure all ids within stories are unique

- packages/web/.storybook/manager-head.html
- packages/web/.storybook/preview-head.html
- packages/web/src/components/gcds-button/stories/gcds-button.stories.js
- packages/web/src/components/gcds-button/stories/overview.mdx
- packages/web/src/components/gcds-side-nav/stories/gcds-side-nav.stories.tsx
- packages/web/src/components/gcds-side-nav/stories/overview.mdx
- packages/web/src/components/gcds-top-nav/stories/gcds-top-nav.stories.tsx
-  Update the button, side-nav and top-nav content
- Update preview wrapper size to match docs content wrapper size
Zenhub tickets for content changes
- [Button](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/690)
- [Side-nav + top-nav](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/763)
> chore(storybook): update storybook content + increase preview wrapper size

- packages/web/.storybook/manager-head.html
Update storybook frame background colour.
> chore(storybook): update frame background colour

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- Fixes https://github.com/cds-snc/design-gc-conception/issues/665
> feat: add templates for new issues (bugs and feat requests)

- .github/ISSUE_TEMPLATE/bug_report.yml
YAML validation was failing - this fixes that
> fix: bug in the bug report

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-checkbox/gcds-checkbox.css
- packages/web/src/components/gcds-fieldset/gcds-fieldset.css
- packages/web/src/components/gcds-hint/gcds-hint.css
- packages/web/src/components/gcds-hint/gcds-hint.tsx
- packages/web/src/components/gcds-hint/test/gcds-hint.spec.ts
- packages/web/src/components/gcds-input/gcds-input.css
- packages/web/src/components/gcds-input/gcds-input.tsx
- packages/web/src/components/gcds-label/gcds-label.css
- packages/web/src/components/gcds-radio-group/gcds-radio-group.css
Design updates for input, label, fieldset, radio, checkbox. It also includes the token package update to the latest version `1.12.2`.
[Zenhub ticket input](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/716)
[Zenhub ticket checkbox](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/662)
[Zenhub ticket radio](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/661)
> refactor: design updates for input, label, fieldset, radio, checkbox

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-details/gcds-details.css
Update details margin + padding tokens to match new design
[Zenhub card](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/814)
> refactor: update details margin + padding tokens to match new design

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/contributions.yml
Updates proposed by @brockhigg10 for the contribution and bug templates
[Zenhub](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/709)
- https://github.com/cds-snc/design-gc-conception/issues/709
> Update issue templates

- .github/ISSUE_TEMPLATE/contributions.yml
Updated the data for the next priorities dropdown
> chore: update issue template for contributing to next priorities

- package.json
Add script to run storybook from the root directory
> ci: easier way to run storybook from root

- package-lock.json
- package.json
Add @stencil/angular-output-target to root package.json so renovate can keep an eye out for updates
- Fixes https://github.com/cds-snc/design-gc-conception/issues/924
> chore(deps): add @stencil/angular-output-target to root package.json

- package-lock.json
- package.json
- packages/vue/tests/app/package-lock.json
- packages/web/package.json
- utils/angular-output-target/package-lock.json
Updating the build scripts to prep for merging the react ssr branch. This change was something we worked on the react ssr branch because once we add the react ssr package to the workspace, lerna doesn't process the packages in the correct order.
This makes it so the web components package installs the angular output target package first as it is a dependency.
> ci: update build for angular

- packages/react-ssr/README.md
Add completed readme with installation instructions to `react-ssr` package.
> docs: Add completed react-ssr package readme

- packages/react-ssr/README.md
Add completed readme to react-ssr branch
> docs: Add new react-ssr readme to newest branch

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-checkbox/readme.md
- packages/web/src/components/gcds-error-message/gcds-error-message.css
- packages/web/src/components/gcds-error-message/gcds-error-message.tsx
- packages/web/src/components/gcds-error-message/readme.md
- packages/web/src/components/gcds-error-message/test/gcds-error-message.spec.ts
- packages/web/src/components/gcds-fieldset/readme.md
- packages/web/src/components/gcds-file-uploader/readme.md
- packages/web/src/components/gcds-icon/readme.md
- packages/web/src/components/gcds-input/readme.md
- packages/web/src/components/gcds-select/readme.md
- packages/web/src/components/gcds-textarea/readme.md
Update error message design to align with the new design.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/810)
> refactor: update error message design

- package-lock.json
- package.json
- packages/web/package.json
This PR fixes the changes applied when PR #586 was merged.
> fix: roll back changes to the angular build process

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-link/gcds-link.css
Add a visited state to the link component.
[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/gcds-components/572)
> feat: add visited state to link component

- .github/workflows/release-generator.yml
- release-please-config.json
Update release please to use new action files, the old version was deprecated.
> build: Update release please

- .github/workflows/release-generator.yml
Fix small typo in workflow file
> build: Fix typo in release generator workflow

- release-please-config.json
Remove prerelease from react-ssr package in release-please-config to see if fixes prerelease PR issues.
> build: remove prerelease from release please

- CHANGELOG.md
> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.
---
> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.
> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de …
> added french for release 0.18.0 to 0.25.0

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-footer/gcds-footer.css
- packages/web/src/components/gcds-nav-group/gcds-nav-group.css
- Fix footer heading font
- Fix white border bug for contextual footer band
- Remove bullet point from mobile nav-group
> fix: various small design bug fixes

- package-lock.json
- packages/web/package.json
Update to latest tokens package to inherit updates for FIP red in signature and legend font weight in date input.
> fix: Update tokens to fix FIP red and date-input legend font weight

- packages/web/.storybook/manager-head.html
- packages/web/.storybook/preview-head.html
Update Storybook spacing styling to use our new tokens.
> chore: update storybook spacing with new tokens

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-breadcrumbs/gcds-breadcrumbs-item.css
Adjusting the breadcrumbs margin and updating the tokens package to align with the design after the typography & spacing update.
> refactor: adjust breadcrumbs margin

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-details/gcds-details.css
Improving the design for the details component when it is being printed.
[Report issue ticket](https://github.com/cds-snc/gcds-components/issues/700).
> style: improve print design for details component

- README.md
- packages/vue/tests/app/.gitignore
- utils/scripts/upload_to_cdn.sh
Cleanup of all things related to lerna. We removed it in a previous PR.
> chore: remove any trace of lerna

- packages/web/README.md
Updating our installation instructions for the web components GCDS package to match the instructions we provide on our documentation site.
> feat: update installation instructions to match documentation site

- packages/web/src/components.d.ts
- packages/web/src/components/gcds-grid/gcds-grid.tsx
- packages/web/src/components/gcds-grid/i18n/i18n.js
- packages/web/src/components/gcds-grid/test/gcds-grid.spec.ts
I added the PR suggestions from @daine, which are mentioned in this [PR](https://github.com/cds-snc/gcds-components/pull/732).
I also added i18n support for gap error messages.
> chore: update grid spacing + test names

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-footer/gcds-footer.css
> style: update the footer component styles

- package-lock.json
- packages/web/package.json
Updating the tokens package to include the latest tokens.
> chore: update tokens package

- package-lock.json
- packages/web/package.json
- packages/web/src/components/gcds-nav-group/gcds-nav-group.css
- packages/web/src/components/gcds-nav-link/gcds-nav-link.css
- packages/web/src/components/gcds-top-nav/gcds-top-nav.css
Updating the design of the top-nav component. We are changing the font size to match the other components in our header. We are also removing the background colour and adding a border to the bottom of the top-nav.
This is the [Zenhub ticket](https://app.zenhub.com/workspaces/gc-design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1352) for the changes.
This PR can't be merged until the tokens from [this tokens PR](https://github.com/cds-snc/gcds-tokens/pull/440) are included.
> style: update top-nav design
